### ISSUE TITLE
HttpResponseException: status code: 416 , reason phrase: Range Not Satisfiable

### ISSUE THREAD

**Issue by wosym** [FTBTeam/FTB-App#1006]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGELICEPEYOG

### Describe the bug

App starts, modpacks don't.  

### Steps to reproduce

* Start FTB app
* Install a modpack (e.g. Direwolf20 1.20)
* Launch is
* Fail...

### Expected behaviour

Runs

### Additional information

This works without issues on my laptop, but not on my Desktop.

The error in the GUI is "java.io.IOException: Failed to execute asset update task." 
But the logs show the following:

``` Caused by: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://resources.download.minecraft.net/34/34051ededea1343bfea6fadd6556e642b6e5cce9' 6 times.
Try 0: net.covers1624.quack.net.HttpResponseException: status code: 416 , reason phrase: 
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask$DownloadValidation.validateResponseCode(NewDownloadTask.java:615)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:254)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:133)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)
```

The status code 416 leads me to believe the app is trying to fetch the wrong file, or the server is trying to provide the wrong file.

**Comment by wosym** [comment]
I just found out it's fixed when using the beta channel?

**Comment by 10407dev** [comment]
I had the same issue and following [these instructions](https://tlannigan.github.io/modded-minecraft-guide/common-issues_ftb-app.html#an-error-occurred-whilst-launching-failed-to-execute-asset-update-task) helped. The file I had to delete had a `__tmp_` prefix along with all the gibberish from the URL.
