### ISSUE TITLE
Neoforge modpacks will not install on FTB App for Ubuntu

### ISSUE THREAD

**Issue by HunterA6** [FTBTeam/FTB-App#1023]
### What Operating System

Linux (Debian)

### Debug Code

FTB-DBGILOSUYOHOL

### Describe the bug

Both the new Direworl20 1.20 modpack and NeoForge mods from the FTB App fail to install

### Steps to reproduce

Open the FTB App and attempt to download any version of the Direwolf20 1.20 mod pack, or even just the NeoForge stand alone mod from the list immediately fails to install and says check the log file.

Checked to ensure the latest version of the FTB App is installed by downloading the app again. It is the same version that I am running currently.

### Expected behaviour

New mod packs, running on NeoForge just install as previous packs have

### Screenshots

![Screenshot from 2023-12-03 10-16-21](https://github.com/FTBTeam/FTB-App/assets/152799378/79f0a57a-d40a-4e0d-b823-ecb4085afeb0)

### Additional information

[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: java.nio.file.NoSuchFileException: opt/FTBA/launcher-202204211116-ac2e189d70-release-all.jar
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:143)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at net.creeperhost.minetogether.lib.util.SignatureUtil.getSignature(SignatureUtil.java:28)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at net.creeperhost.creeperlauncher.Constants.<clinit>(Constants.java:119)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:92)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.minetogether.lib.util.SignatureUtil:getSignature:38]: 	at install4j.net.creeperhost.creeperlauncher.CreeperLauncher.main(Unknown Source)
[09:57:28] [main/INFO] [STDOUT]: [net.creeperhost.creeperlauncher.CreeperLauncher:main:92]: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[09:57:28] [main/INFO] [Instances]: Reloading instances..
[09:57:28] [main/INFO] [Instances]: Skipping Cloud instance reload.
[09:57:28] [ForkJoinPool.commonPool-worker-4/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/3acccbf4-48d3-4cf8-a67a-c52ea08185d4/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-6/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/e659dd38-bdb2-4cae-8e5c-d14e2beb458e/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-4/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/359b868c-48e0-4774-bcde-89ad770cbfe0/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-1/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/a68d3981-52f8-483f-a7c7-7793adf327dd/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-1/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/38d29a75-d8ce-4a97-9d6d-9a7759d8e89c/instance.json
[09:57:28] [main/INFO] [Instances]: Loaded 8 out of 8 instances in 222ms(222104141ns).
[09:57:28] [main/INFO] [Instances]: Finished instance reload in 228ms(228185417ns)
[09:57:28] [main/INFO] [FTB Subprocess]: Electron integration mode
[09:57:28] [main/INFO] [FTB Subprocess]: No PID args specified
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: java.nio.file.FileSystemException: /opt/FTBA/bin/ftb-app: Operation not permitted
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:277)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:299)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2167)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at net.creeperhost.creeperlauncher.util.FileUtils.setFilePermissions(FileUtils.java:98)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at net.creeperhost.creeperlauncher.CreeperLauncher.startElectron(CreeperLauncher.java:507)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:155)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
[09:57:28] [main/INFO] [STDERR]: [net.creeperhost.creeperlauncher.util.FileUtils:setFilePermissions:101]: 	at install4j.net.creeperhost.creeperlauncher.CreeperLauncher.main(Unknown Source)
[09:57:28] [WebSocketSelector-41/INFO] [Websockets API]: Server started successfully - 202204211116-ac2e189d70-release
[09:57:28] [main/INFO] [FTB Subprocess]: Starting Electron: /opt/FTBA/bin/ftb-app --ws 17632:26f36c43-3cdd-47b3-bead-17bee245e2db --pid 12223
[09:57:28] [main/INFO] [Instances]: Reloading instances..
[09:57:28] [main/INFO] [Instances]: Skipping Cloud instance reload.
[09:57:28] [ForkJoinPool.commonPool-worker-2/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/e659dd38-bdb2-4cae-8e5c-d14e2beb458e/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-3/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/a68d3981-52f8-483f-a7c7-7793adf327dd/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-2/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/3acccbf4-48d3-4cf8-a67a-c52ea08185d4/instance.json
[09:57:28] [main/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/359b868c-48e0-4774-bcde-89ad770cbfe0/instance.json
[09:57:28] [ForkJoinPool.commonPool-worker-2/ERROR] [Instances]: Instance install never completed, Ignoring. /home/chris/.ftba/instances/38d29a75-d8ce-4a97-9d6d-9a7759d8e89c/instance.json
[09:57:28] [main/INFO] [Instances]: Loaded 8 out of 8 instances in 62ms(62680885ns).
[09:57:28] [main/INFO] [Instances]: Finished instance reload in 64ms(64729349ns)
[09:57:29] [ForkJoinPool.commonPool-worker-6/INFO] [FTB Subprocess]: 09:57:29.191 › We have a --ws
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: 09:57:29.201 › electron-log.transports.file: Can't write to /opt/FTBA/bin/electron.log Error: EACCES: permission denied, open '/opt/FTBA/bin/electron.log'
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at Object.openSync (node:fs:585:3)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
[09:57:29] [ForkJoinPool.commonPool-worker-6/INFO] [FTB Subprocess]: 09:57:29.204 › Got the lock
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at Object.writeFileSync (node:fs:2153:35)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at l.testFileWriting (/opt/FTBA/bin/resources/app.asar/background.js:1:216991)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at l.createFile (/opt/FTBA/bin/resources/app.asar/background.js:1:216524)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at l.provide (/opt/FTBA/bin/resources/app.asar/background.js:1:216351)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at d (/opt/FTBA/bin/resources/app.asar/background.js:1:213701)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at h (/opt/FTBA/bin/resources/app.asar/background.js:1:213200)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at i (/opt/FTBA/bin/resources/app.asar/background.js:1:53636)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:     at n (/opt/FTBA/bin/resources/app.asar/background.js:1:53428)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: 09:57:29.389 › (node:12304) ExtensionLoadWarning: Warnings loading extension at /home/chris/.config/ftb-app/extensions/nhdogjmejiglipccpnnnanhbledajbpd:
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]:   Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: 
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: (Use `ftb-app --trace-warnings ...` to show where the warning was created)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.487084:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.506439:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.507442:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.508329:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.509316:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.510256:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.511268:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.512151:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.513023:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.513291:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.513503:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.513683:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.513899:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.514081:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.514238:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.514400:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.514556:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.514711:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.514878:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.515056:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.515211:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.515378:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.515553:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.515722:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.515902:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.516067:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.516268:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.516462:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.516688:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.516918:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.517168:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.517364:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.517527:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.517708:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.517876:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.518033:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.518195:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.518379:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.518534:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.518697:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:29] [ForkJoinPool.commonPool-worker-4/ERROR] [FTB Subprocess]: [12343:1203/095729.518896:ERROR:gbm_wrapper.cc(275)] Failed to export buffer to dma_buf: No such file or directory (2)
[09:57:30] [WebSocketWorker-33/INFO] [Websockets API]: Front end connected: /127.0.0.1:48832
[09:57:58] [ForkJoinPool-1-worker-1/INFO] [net.creeperhost.creeperlauncher.data.modpack.ModpackManifest]: Querying Modpack version manifest: https://api.modpacks.ch/public/modpack/119
[09:57:59] [ForkJoinPool-1-worker-1/INFO] [net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest]: Querying Modpack version manifest: https://api.modpacks.ch/public/modpack/119/11393
[09:58:00] [ForkJoinPool-1-worker-1/ERROR] [net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler]: Fatal exception configuring modpack installation.
java.lang.IllegalArgumentException: Unknown ModLoader name: neoforge
	at net.creeperhost.creeperlauncher.install.tasks.modloader.ModLoaderInstallTask.createInstallTask(ModLoaderInstallTask.java:50) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepareModLoader(InstanceInstaller.java:346) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepare(InstanceInstaller.java:181) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler.handleInstall(InstallInstanceHandler.java:82) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler.handle(InstallInstanceHandler.java:68) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler.handle(InstallInstanceHandler.java:23) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:104) ~[launcher-202204211116-ac2e189d70-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]

**Comment by MichaelHillcox** [comment]
You're running a pretty old version of the app, please update and try again, you can get the latest linux version here

https://apps.modpacks.ch/FTBApp/release/202312051208-42d5498370/FTBA_unix_202312051208-42d5498370.sh

**Comment by HunterA6** [comment]
That did the trick. Thanks
