### ISSUE TITLE
Can't open FTB App

### ISSUE THREAD

**Issue by Whaith** [FTBTeam/FTB-App#1025]
### What Operating System

MacOS (Latest)

### Debug Code

FTB-DBGEKEFACOFEV

### Describe the bug

FTB App is stucked/can't open.

### Steps to reproduce

1. Open FTB App
2. Wait

### Expected behaviour

Open the launcher

**Comment by SirSeim** [comment]
I started having the same issue today. As recently as yesterday I was able to open the app. Previously, what I was accustomed to seeing was `FTBApp` being the thing I opened, and then after a few seconds, a second icon would show up in my Dock under the name `ftbapp`, but which I could not launch directly.

I've tried all combinations of wiping out the app, the `.ftba` folder in Application Support, and restarting. Opening up `FTBApp.app`, I do see an `error.log`:
```
java.nio.file.NoSuchFileException: Applications/FTBApp.app/Contents/Resources/app/launcher-202312041956-1375ba067c-all.jar
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1264)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:143)
	at net.creeperhost.minetogether.lib.util.SignatureUtil.getSignature(SignatureUtil.java:28)
	at net.creeperhost.creeperlauncher.Constants.<clinit>(Constants.java:112)
	at net.creeperhost.creeperlauncher.CreeperLauncher.lambda$static$0(CreeperLauncher.java:69)
	at io.sentry.Sentry.init(Sentry.java:139)
	at io.sentry.Sentry.init(Sentry.java:126)
	at net.creeperhost.creeperlauncher.CreeperLauncher.<clinit>(CreeperLauncher.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
```
`launcher-202312041956-1375ba067c-all.jar` is present right alongside `error.log`. At my first glance, it seems weird that java was looking in `Applications/...` and not `/Applications/...`.

Activity Monitor shows cpu activity for `FTBApp` initially on launch, but the drops to 0.1 forever which accompanies the icon stopping it's bouncing in the Dock.

With fresh versions of the app downloaded from the site, it appears to instantly go into this stuck state. I happened to have an older download of the dmg and this error still occurs, though it takes longer. I see the second `ftbapp` show up as expected, but then goes away and `FTBApp` restarts. I assume this is an auto update cycle.

Happy to give more context if there's specific things that would be helpful for debugging.

**Comment by jfmoots** [comment]
Exact same error log here on a Mac. Just started happening tonight.

**Comment by JackdawIsland** [comment]
Same issue Macbook Air M1. Played perfectly fine Saturday. App shows open in Activity Monitor. I opened it and got to the launcher screen and it closed, I thought it was just a crash and havent been able to re open it since

**Comment by mccarthy-thomas** [comment]
Same issue here with the same `error.log`. Worked about 8 hours ago, but doesn't launch properly now.

**Comment by knzconnor** [comment]
@SirSeim it always used to the the weird shuffle with two different apps/versions on the dock, one of which you couldn't open directly without just stalling. So that part isn't new, ime. But yeah it just stalls out completely, when it ran fine earlier today.  And FTB making people pull their packs from other launchers I guess I'm just not playing Genesis any further rn. :/

**Comment by JackdawIsland** [comment]
I happened to have the old dmg file in my downloads folder. I tried installing the old version again and got the same bug. I agreen with @knzconnor its very frustrating because CurseForge works for me, but has an old version of the pack which means I can't play the server me and a friend have spent the last month on together... We just entered the mid-game too which means starting over now is almost out of the question

**Comment by jfmoots** [comment]
I installed MultiMC and imported my FTB One setup and it launches. I’m betting there is a web service with one of the Ad companies plugged in to the FTB launcher keeping it from starting. Just a guess…

**Comment by knzconnor** [comment]
@jfmoots yeah right after complaining I (re)installed (new machine) Prism and imported it and it worked fine. :)

**Comment by jfmoots** [comment]
> @jfmoots yeah right after complaining I (re)installed (new machine) Prism and imported it and it worked fine. :)

Does Prism support AARM Java? The problem with MultiMC is you need to use the X86 Java and then that goes through Rosetta and really impacts performance. It’s night and day…

**Comment by JackdawIsland** [comment]
@jfmoots I'm not very good when it comes to this kind of thing but I can't get Prisim to launch properly... It says my java is the incorrect version. Honestly I'm pretty frustrated that I can't download this pack on a launcher that works in the meantime while FTB gets this fixed

**Comment by meeker68** [comment]
I tried running the "FTB App.app" within the package and got this crash report:

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
Referenced from: <4C4C4460-5555-3144-A1E7-7949DDD09C84> /Applications/FTBApp.app/Contents/Resources/app/bin/FTB App.app/Contents/MacOS/FTB App
Reason: tried: '/Applications/FTBApp.app/Contents/Resources/app/bin/FTB App.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Applications/FTBApp.app/Contents/Resources/app/bin/FTB App.app/Contents/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file), '/System/Library/Frameworks/Electron Framework.framework/Electron Framework' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

---

The path might need to be '/Applications/FTBApp.app/Contents/Resources/app/bin/FTB App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework' (at least that is where it is on my system)

Not sure if this means anything as I'm not familiar with this kind of code.

I also had this running a day ago with no issues.  Wasn't there also a Ventura security update recently?

**Comment by RubenAhlhaus** [comment]
I'm having the exact same issue here on an Intel mac running macOS Big Sur. The launcher was working fine yesterday but won't open today. If I reinstall FTB (using an old dmg) I can get the launcher to open for about 10 seconds after which it disappears and then fails to open at all.

**Comment by MichaelHillcox** [comment]
We've reset the product name which should resolve this issue. I'll update the issue with download links to the fixed version once they're available. 

Sorry to everyone that was effected by this change

**Comment by MichaelHillcox** [comment]
https://apps.modpacks.ch/FTBApp/release/202312051126-a5c2b18911/

You will find the relevant DMG or Linux (I recommend using the .sh as we've seen issues with other file types) here. This should be a fixed version.  Please let me know if you have any issues

**Comment by MichaelHillcox** [comment]
I've just had the same thing, I'm building another version now as the CI may have just borked the update

**Comment by samip5** [comment]
> https://apps.modpacks.ch/FTBApp/release/202312051126-a5c2b18911/
> 
> You will find the relevant DMG or Linux (I recommend using the .sh as we've seen issues with other file types) here. This should be a fixed version. Please let me know if you have any issues

Tried that one, with the sh version but unfortunately results are unable to open it.

```
sm@Orion /A/F/bin> ls
LICENSE.electron.txt     chrome_100_percent.pak   ftb-app*                 libGLESv2.so             libvulkan.so.1           resources.pak            vk_swiftshader_icd.json
LICENSES.chromium.html   chrome_200_percent.pak   icudtl.dat               libffmpeg.so             locales/                 snapshot_blob.bin
chrome-sandbox           chrome_crashpad_handler  libEGL.so                libvk_swiftshader.so     resources/               v8_context_snapshot.bin
sm@Orion /A/F/bin> ./ftb-app
exec: Failed to execute process: './ftb-app' the file could not be run by the operating system.
sm@Orion /A/F/bin [126]> file ftb-app
ftb-app: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=a9fe2e68990a4d899fb03e753dda9013e974c849, not stripped
sm@Orion /A/F/bin> uname -m
arm64
```

**Comment by JackdawIsland** [comment]
Same issue here, "app is damaged and cannot be opened"

**Comment by MichaelHillcox** [comment]
https://apps.modpacks.ch/FTBApp/release/202312051208-42d5498370/FTBA_macos_202312051208-42d5498370.dmg
https://apps.modpacks.ch/FTBApp/release/202312051208-42d5498370/FTBA_unix_202312051208-42d5498370.sh

Please try the above versions depending on your OS. I've had success with these builds on my machine

**Comment by samip5** [comment]
@MichaelHillcox Unfortunately:
<img width="245" alt="Screenshot 2023-12-05 at 14 25 56" src="https://github.com/FTBTeam/FTB-App/assets/1703002/1fe86480-bfba-4968-9009-40e0946bedaa">

**Comment by MichaelHillcox** [comment]
@samip5 That's normal, just go to settings -> privacy and security -> and allow the FTB App

**Comment by jgreen417** [comment]
Working

**Comment by SaronGrave** [comment]
DMG works for me!

**Comment by samip5** [comment]
> @samip5 That's normal, just go to settings -> privacy and security -> and allow the FTB App

Yeah, sorry. Skill issue, but yes that works. :)

**Comment by MichaelHillcox** [comment]
Awesome to hear it's working again! I'm a Mac user myself so sorry again for the inconvenience this update caused.

**Comment by MichaelHillcox** [comment]
Closing now as this has been resovled :+1: Thanks again everyone that helped test and gave me quick feedback <3
