### ISSUE TITLE
FTB App Won't open

### ISSUE THREAD

**Issue by The-One-and-only-Lookas-the-L** [FTBTeam/FTB-App#1081]
### What Operating System

Windows 10

### Debug Code

NO CODE

### Describe the bug

The app won't open.
tried reinstalling and running with admin
ps: the file does indeed exist even tho monsieur debug says nop

### Steps to reproduce

1. Open the FTB App
2. See the screen with "Ooops this doesn't look right"

### Expected behaviour

Just the app to open normally

### Additional information

#  System Information

 INFO  OS: Microsoft Windows 10 Pro (10.0.19045)
 INFO  CPU: 12th Gen Intel(R) Core(TM) i3-12100F (GenuineIntel)
 INFO  Memory: 8.29 GiB / 15.86 GiB (52.00% used)
 INFO  Killing FTB App

# FTB App Checks

# Network requests checks

 SUCCESS  https://api.modpacks.ch/public/api/ping returned expected results
 SUCCESS  https://api.creeper.host/api/health returned expected results
 SUCCESS  https://maven.creeperhost.net returned expected results
 SUCCESS  https://maven.fabricmc.net returned expected results
 SUCCESS  https://maven.minecraftforge.net/net/minecraftforge/forge/maven-metadata.xml returned expected results
 SUCCESS  FTB App directory (AppData): file/directory exists

## Validating App structure

 SUCCESS  Minecraft bin directory: file/directory exists

## App info

 INFO  Located app at C:\Users\Anwender\AppData\Local/.ftba
  ERROR   Error opening version.json: open C:\Users\MYUSERNAME\AppData\Local/Overwolf/Extensions/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.24.104.1636/version.json: The system cannot find the file specified.
 INFO  App version: 1.24.104.1636
 INFO  Backend version:
 INFO  Web version:
 INFO  Branch:
 SUCCESS  Does app_settings.json exist?: file/directory exists
 INFO  Instance Location:  C:\Users\Anwender\AppData\Local\.ftba\instances

# Check for instances

 SUCCESS  instances directory: file/directory exists
 INFO  found instance:  cb524e5b-ceb0-4900-885a-7e6ffeca7246
 INFO  Name: FTB Inferno
 INFO  Version: 1.2.1
 INFO  Version ID: 2279
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 WARNING  cb524e5b-ceb0-4900-885a-7e6ffeca7246 logs folder: file/directory does not exist
 SUCCESS  cb524e5b-ceb0-4900-885a-7e6ffeca7246 instance.json: file/directory exists
 SUCCESS  cb524e5b-ceb0-4900-885a-7e6ffeca7246 instance.json: json is valid
 INFO  found instance:  e0ab5f28-42a8-4aa8-b156-3c270d8e1db8
 INFO  Name: FTB Presents Stoneblock 2
 INFO  Version: 1.22.0
 INFO  Version ID: 2115
 INFO  Memory: 6144
 INFO  Min/Rec Memory: 4096/6144
 INFO  Custom Args:
 INFO  Embedded JRE: true
 INFO  Is Modified: false
 SUCCESS  e0ab5f28-42a8-4aa8-b156-3c270d8e1db8 logs folder: file/directory exists
 INFO  console.log last modified: 27/02/2024 20:19:54
 INFO  debug.log last modified: 27/02/2024 20:19:54
 INFO  latest.log last modified: 27/02/2024 20:19:54
▀  Checking for e0ab5f28-42a8-4aa8-b156-3c270d8e1db8 instance.json (0s)ctory exists
 SUCCESS  e0ab5f28-42a8-4aa8-b156-3c270d8e1db8 instance.json: json is valid

# Upload logs

 SUCCESS  Uploaded settings.json: https://pste.ch/ihegoxotop
 SUCCESS  Uploaded version_manifest.json: https://pste.ch/gurocupuyu

**Comment by The-One-and-only-Lookas-the-L** [comment]
Yeah im sorry, the app fvcking crashed mid reporting :)


# Upload logs

 SUCCESS  Uploaded settings.json: https://pste.ch/niducawuti
 SUCCESS  Uploaded version_manifest.json: https://pste.ch/eqigahosug
 WARNING  Uploading console.log: failed to upload - file too large
 INFO  Trying again with transfer.sh
  ERROR   Uploading console.log: failed to upload
  ERROR   open C:\Users\Anwender\AppData\Local\.ftba\instances\e0ab5f28-42a8-4aa8-b156-3c270d8e1db8\logs\console.log/console.log: The system cannot find the path specified.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x11815ac]

goroutine 1 [running]:
net/http.(*Client).do(0x1661000?, 0x0)
        /usr/local/go/src/net/http/client.go:590 +0xcc
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:581
main.uploadBigFile({0xc0004da150?, 0xc000243868?}, {0xc000326720, 0xb})
        /go/src/git.ftb.dev/Jake_Evans/ftb-debug/utils.go:253 +0x1b0
main.newUploadFile({0xc0004da150, 0x65}, {0xc000326720, 0xb})
        /go/src/git.ftb.dev/Jake_Evans/ftb-debug/utils.go:178 +0x4ee
main.uploadFiles()
        /go/src/git.ftb.dev/Jake_Evans/ftb-debug/main.go:224 +0xb85
main.main()
        /go/src/git.ftb.dev/Jake_Evans/ftb-debug/main.go:174 +0x1aa5

**Comment by The-One-and-only-Lookas-the-L** [comment]
ok so i have no clue why but i booted a windows backup and now everythings back to normal

still thanks for the help <3
