### ISSUE TITLE
Can't add mods to unlocked modpack (download hangs)

### ISSUE THREAD

**Issue by hvdklauw** [FTBTeam/FTB-App#1106]
### What Operating System

Windows 11

### Debug Code

FTB-DBGRIWADUJINI

### Describe the bug

Just hangs on the download screen on 0% progress.

The debug log shows a null pointer exeption at the bottom:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionModsManifest$Mod.getCurseSlug(ModpackVersionModsManifest.java:87) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.CurseMetadataCache.getCurseMeta(CurseMetadataCache.java:68) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.Instance.getMods(Instance.java:558) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.install.ModInstaller.resolve(ModInstaller.java:90) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:18) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketHandler.lambda$handleMessage$0(WebSocketHandler.java:161) ~[launcher-86d919d5e9-all.jar:?]
	... 7 more
```

All the logs: https://pste.ch/uxorabokiy

### Steps to reproduce

Download FTB builders paradise 2
Unlock it
Add a mod (create addon or callable horse)
See it hang and nothing happening.

### Expected behaviour

For the mod to be downloaded and added to the modpack

### Additional information

https://pste.ch/uxorabokiy

**Comment by LoneStar-** [comment]
Having the same issues trying to install mods to any instance, progress just stays at 0%

`[19:57:00] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Building instance mods list..
[19:57:00] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: List built 254 mods.
[19:57:01] [ModVersionCache 12/ERROR] [net.creeperhost.creeperlauncher.util.ModVersionCache]: Error whilst querying mod from ram cache.
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Failed to query mod manifest for: 247007
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.ModVersionCache.lambda$queryMod$0(ModVersionCache.java:118) ~[launcher-86d919d5e9-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to query mod manifest for: 247007
	at net.creeperhost.creeperlauncher.util.ModVersionCache$2.load(ModVersionCache.java:56) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.ModVersionCache$2.load(ModVersionCache.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[launcher-86d919d5e9-all.jar:?]
	... 8 more
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a long but was BOOLEAN at line 26 column 21 path $.updated
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1107) ~[launcher-86d919d5e9-all.jar:?]
	at net.covers1624.quack.gson.JsonUtils.parse(JsonUtils.java:92) ~[launcher-86d919d5e9-all.jar:?]
	at net.covers1624.quack.gson.JsonUtils.parse(JsonUtils.java:61) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.data.mod.ModManifest.queryManifest(ModManifest.java:76) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.data.mod.ModManifest.queryManifest(ModManifest.java:63) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.ModVersionCache$2.load(ModVersionCache.java:54) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.ModVersionCache$2.load(ModVersionCache.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[launcher-86d919d5e9-all.jar:?]
	... 8 more
Caused by: java.lang.IllegalStateException: Expected a long but was BOOLEAN at line 26 column 21 path $.updated
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:973) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:331) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:323) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1227) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1137) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1107) ~[launcher-86d919d5e9-all.jar:?]
	at net.covers1624.quack.gson.JsonUtils.parse(JsonUtils.java:92) ~[launcher-86d919d5e9-all.jar:?]
	at net.covers1624.quack.gson.JsonUtils.parse(JsonUtils.java:61) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.data.mod.ModManifest.queryManifest(ModManifest.java:76) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.data.mod.ModManifest.queryManifest(ModManifest.java:63) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.ModVersionCache$2.load(ModVersionCache.java:54) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.ModVersionCache$2.load(ModVersionCache.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159) ~[launcher-86d919d5e9-all.jar:?]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[launcher-86d919d5e9-all.jar:?]
	... 8 more
[19:57:16] [ForkJoinPool-1-worker-127/INFO] [net.creeperhost.creeperlauncher.install.ModInstaller]: Resolving install of mod 446870 version 4299157
[19:57:17] [ForkJoinPool-1-worker-127/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Building instance mods list..
[19:57:17] [ForkJoinPool-1-worker-127/ERROR] [net.creeperhost.creeperlauncher.api.WebSocketHandler]: Error handling message
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionModsManifest$Mod.getCurseSlug(ModpackVersionModsManifest.java:87) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.CurseMetadataCache.getCurseMeta(CurseMetadataCache.java:68) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.Instance.getMods(Instance.java:558) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.install.ModInstaller.resolve(ModInstaller.java:90) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:18) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketHandler.lambda$handleMessage$0(WebSocketHandler.java:161) ~[launcher-86d919d5e9-all.jar:?]
	... 7 more
`

**Comment by shutter-germany** [comment]
same here. Tried to Install Tetra for the Direwolf20 1.20 pack.

```
[12:21:06.481] [ForkJoinPool-1-worker-4/INFO] [net.creeperhost.creeperlauncher.install.ModInstaller]: Resolving install of mod 289712 version 5236744
[12:21:07.417] [ForkJoinPool-1-worker-4/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Building instance mods list..
[12:21:07.420] [ForkJoinPool-1-worker-4/ERROR] [net.creeperhost.creeperlauncher.api.WebSocketHandler]: Error handling message
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionModsManifest$Mod.getCurseSlug(ModpackVersionModsManifest.java:87) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.CurseMetadataCache.getCurseMeta(CurseMetadataCache.java:68) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.Instance.getMods(Instance.java:558) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.install.ModInstaller.resolve(ModInstaller.java:90) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:18) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketHandler.lambda$handleMessage$0(WebSocketHandler.java:161) ~[launcher-86d919d5e9-all.jar:?]
	... 7 more
```

**Comment by coldfusion818** [comment]
I'm having the same issue, when trying to add a mod to an existing modpack or a custom instance.

`[22:06:59.802] [main/DEBUG] [net.creeperhost.creeperlauncher.storage.CredentialStorage]: Interface: Microsoft Wi-Fi Direct Virtual Adapter #4 : wlan3
[22:06:59.805] [main/INFO] [net.creeperhost.creeperlauncher.storage.CredentialStorage]: Loading credentials for user
[22:06:59.806] [main/WARN] [net.creeperhost.creeperlauncher.storage.CredentialStorage]: Failed to load credentials, credentials file does not exist
[22:06:59.810] [main/INFO] [net.creeperhost.creeperlauncher.util.ProxyUtils]: Loading proxy configuration. none  -1, Without Authentication.
[22:06:59.813] [main/TRACE] [net.creeperhost.creeperlauncher.util.SSLUtils]: Injecting LoggingX509TrustManager into OkHTTP.
[22:06:59.814] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[22:06:59.856] [ForkJoinPool.commonPool-worker-3/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\6ab5ce80-bc06-4387-9e1e-3a30a30c05c4\instance.json
[22:06:59.856] [ForkJoinPool.commonPool-worker-8/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\50a3d4a8-576c-4d43-b8a7-9f99762d6524\instance.json
[22:06:59.872] [main/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\817a7554-faf9-4472-bba9-aea3f39f6a93\instance.json
[22:06:59.872] [ForkJoinPool.commonPool-worker-2/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\f1c5346a-279e-4a33-ba8d-4128bffd7210\instance.json
[22:06:59.884] [ForkJoinPool.commonPool-worker-1/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\1d7fcef9-3c69-42e5-8af0-db8da6c339c9\instance.json
[22:06:59.897] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 4 out of 4 instances in 80ms(80474400ns).
[22:06:59.898] [main/INFO] [net.creeperhost.creeperlauncher.instance.cloud.CloudSaveManager]: Skipping loading cloud saves. Not configured.
[22:06:59.898] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 84ms(84127900ns)
[22:06:59.905] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Args: {pid=53148, overwolf=}
[22:06:59.905] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Overwolf integration mode
[22:06:59.942] [main/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Starting websocket server on 127.0.0.1:59946
[22:06:59.955] [main/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: Websocket started!
[22:06:59.956] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: {T:CI={p:59946;s:ea36881c-e692-476a-935b-091bd869135c}}
[22:07:01.214] [NanoHttpd Request Processor (#1)/INFO] [net.creeperhost.creeperlauncher.api.NanoHttpdWebsocketServer]: New connection to 127.0.0.1.
[22:07:01.432] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[22:07:01.436] [ForkJoinPool-1-worker-3/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\817a7554-faf9-4472-bba9-aea3f39f6a93\instance.json
[22:07:01.436] [ForkJoinPool-1-worker-4/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\1d7fcef9-3c69-42e5-8af0-db8da6c339c9\instance.json
[22:07:01.438] [ForkJoinPool-1-worker-9/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\f1c5346a-279e-4a33-ba8d-4128bffd7210\instance.json
[22:07:01.439] [ForkJoinPool-1-worker-6/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\50a3d4a8-576c-4d43-b8a7-9f99762d6524\instance.json
[22:07:01.438] [ForkJoinPool-1-worker-7/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Matthew\AppData\Local\.ftba\instances\6ab5ce80-bc06-4387-9e1e-3a30a30c05c4\instance.json
[22:07:01.448] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 4 out of 4 instances in 14ms(14553100ns).
[22:07:01.448] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.instance.cloud.CloudSaveManager]: Skipping loading cloud saves. Not configured.
[22:07:01.449] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 16ms(16528200ns)
[22:07:02.245] [DNS Report Executor 0/INFO] [net.creeperhost.creeperlauncher.util.DNSDebug]: DNS Report:
Chain:
CLOUDFLARE - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
GOOGLE - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
CREEPERHOST - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
System - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
Important Hosts:
sessionserver.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.246.40, 13.107.213.40, 2620:1ec:bdf:0:0:0:0:40, 2620:1ec:46:0:0:0:0:40]
launchermeta.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.213.40, 13.107.246.40, 2620:1ec:bdf:0:0:0:0:40, 2620:1ec:46:0:0:0:0:40]
api.mojang.com
    From  : CLOUDFLARE
    Answer: [2620:1ec:bdf:0:0:0:0:40, 2620:1ec:46:0:0:0:0:40, 13.107.213.40, 13.107.246.40]
session.minecraft.net
    From  : CLOUDFLARE
    Answer: [13.107.246.41, 13.107.213.41, 2620:1ec:bdf:0:0:0:0:41, 2620:1ec:46:0:0:0:0:41]
piston-meta.mojang.com
    From  : CLOUDFLARE
    Answer: [2620:1ec:bdf:0:0:0:0:40, 2620:1ec:46:0:0:0:0:40, 13.107.246.40, 13.107.213.40]
api.modpacks.ch
    From  : CLOUDFLARE
    Answer: [185.57.191.115]
api.creeperhost.net
    From  : CLOUDFLARE
    Answer: [185.57.191.115]
dist.modpacks.ch
    From  : CLOUDFLARE
    Answer: [172.67.223.38, 104.21.46.38, 2606:4700:3032:0:0:0:ac43:df26, 2606:4700:3037:0:0:0:6815:2e26]
maven.creeperhost.net
    From  : CLOUDFLARE
    Answer: [104.26.5.5, 104.26.4.5, 172.67.70.147, 2606:4700:20:0:0:0:681a:405, 2606:4700:20:0:0:0:681a:505, 2606:4700:20:0:0:0:ac43:4693]
maven.fabricmc.net
    From  : CLOUDFLARE
    Answer: [104.21.33.240, 172.67.151.177, 2606:4700:3033:0:0:0:ac43:97b1, 2606:4700:3037:0:0:0:6815:21f0]
maven.minecraftforge.net
    From  : CLOUDFLARE
    Answer: [172.67.161.211, 104.21.58.163, 2606:4700:3032:0:0:0:6815:3aa3, 2606:4700:3036:0:0:0:ac43:a1d3]
maven.neoforged.net
    From  : CLOUDFLARE
    Answer: [2606:4700:3037:0:0:0:6815:59e2, 2606:4700:3034:0:0:0:ac43:a5bb, 172.67.165.187, 104.21.89.226]

[22:13:21.409] [ForkJoinPool-1-worker-6/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Building instance mods list..
[22:13:26.673] [ForkJoinPool-1-worker-6/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: List built 305 mods.
[22:14:00.247] [ForkJoinPool-1-worker-63/INFO] [net.creeperhost.creeperlauncher.install.ModInstaller]: Resolving install of mod 559312 version 5274721
[22:14:00.802] [ForkJoinPool-1-worker-63/INFO] [net.creeperhost.creeperlauncher.pack.Instance]: Building instance mods list..
[22:14:00.822] [ForkJoinPool-1-worker-63/ERROR] [net.creeperhost.creeperlauncher.api.WebSocketHandler]: Error handling message
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionModsManifest$Mod.getCurseSlug(ModpackVersionModsManifest.java:87) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.util.CurseMetadataCache.getCurseMeta(CurseMetadataCache.java:68) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.Instance.getMods(Instance.java:558) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.install.ModInstaller.resolve(ModInstaller.java:90) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:50) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstanceInstallModHandler.handle(InstanceInstallModHandler.java:18) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-86d919d5e9-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketHandler.lambda$handleMessage$0(WebSocketHandler.java:161) ~[launcher-86d919d5e9-all.jar:?]
	... 7 more
`

**Comment by LoneStar-** [comment]
OK, I kinda found a work around for this issue. 
If I go to "AppData\Local\Overwolf\Extensions\cmogmmciplgmocnhikmphehmeecmpaggknkjlbag" and delete the 1.25.8 folder, app downloads and installs mods fine.

Note:
The "cmogmmciplgmocnhikmphehmeecmpaggknkjlbag" folder will be different from what's on your PC. If you are running the Overwolf launcher, right click the FTB shortcut > properties > click shortcut tab and look at the target field. 

You should have something like 
"C:\Program Files (x86)\Overwolf\OverwolfLauncher.exe" -launchapp cmogmmciplgmocnhikmphehmeecmpaggknkjlbag -from-startmenu".

In above command, "cmogmmciplgmocnhikmphehmeecmpaggknkjlbag" would be your FTB extension folder, go in and delete the 1.25.8 folder and you should be able to download and install mods to existing mod pack. One drawback, you will have to delete this folder every time you want to install a new mod. I have created a batch file that automatically deletes the folder then launches the FTB app.

**Comment by BestBucko** [comment]
> OK, I kinda found a work around for this issue. If I go to "AppData\Local\Overwolf\Extensions\cmogmmciplgmocnhikmphehmeecmpaggknkjlbag" and delete the 1.25.8 folder, app downloads and installs mods fine.
> 
> Note: The "cmogmmciplgmocnhikmphehmeecmpaggknkjlbag" folder will be different from what's on your PC. If you are running the Overwolf launcher, right click the FTB shortcut > properties > click shortcut tab and look at the target field.
> 
> You should have something like "C:\Program Files (x86)\Overwolf\OverwolfLauncher.exe" -launchapp cmogmmciplgmocnhikmphehmeecmpaggknkjlbag -from-startmenu".
> 
> In above command, "cmogmmciplgmocnhikmphehmeecmpaggknkjlbag" would be your FTB extension folder, go in and delete the 1.25.8 folder and you should be able to download and install mods to existing mod pack. One drawback, you will have to delete this folder every time you want to install a new mod. I have created a batch file that automatically deletes the folder then launches the FTB app.

Wow, this worked instantly for me, a bit of a clunky workaround but got my mods added in easily once it launched as 1.25.7

**Comment by LoneStar-** [comment]
> Is anyone still experiencing this issue on the latest version of the app?

As far as I know, this was fixed a few versions ago. I stopped using the app, so I couldn't give you a def answer
