### ISSUE TITLE
Cannot run my instances

### ISSUE THREAD

**Issue by AlexGritsay** [FTBTeam/FTB-App#1128]
### What Operating System

Windows 11

### Debug Code

FTB-DBGWUJESITUDU

### Describe the bug

I don't know what actually caused this problem. Actually, an original Minecraft launcher got an update this day as well, so probably it is related somehow.
I tried checking log file, and this is what it says:
[13:59:04] [Instance Thread [4]/ERROR] [net.creeperhost.creeperlauncher.pack.InstanceLauncher]: Failed to start minecraft process!
java.io.IOException: Cannot run program "C:\Users\         \AppData\Local\.ftba\bin\runtime\jdk-17.0.4+8-jre\bin\javaw.exe" (in directory "C:\Users\Александр\AppData\Local\.ftba\instances\stacia 2 expert"): CreateProcess error=2, (Cannot locate file)
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at java.lang.ProcessBuilder.start(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.lambda$launch$3(InstanceLauncher.java:163) ~[launcher-3fd58fbe04-all.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.io.IOException: CreateProcess error=2, Не удается найти указанный файл
	at java.lang.ProcessImpl.create(Native Method) ~[?:?]
	at java.lang.ProcessImpl.<init>(Unknown Source) ~[?:?]
	at java.lang.ProcessImpl.start(Unknown Source) ~[?:?]
	... 4 more

### Steps to reproduce

1. Start any modpack
2. See that app is unable to start minecraft launcher

### Expected behaviour

i just want to play lol T_T

**Comment by MichaelHillcox** [comment]
Does this file exist? `\AppData\Local.ftba\bin\runtime\jdk-17.0.4+8-jre\bin\javaw.exe`
