### ISSUE TITLE
[Bug] Can't download forge modpacks

### ISSUE THREAD

**Issue by x1msoc** [FTBTeam/FTB-App#1162]
### What Operating System

Linux (Other)

### Debug Code

FTB-DBGAMITEGASIH

### Describe the bug

I'm unable to download any **Forge** modpacks. I can download any **Fabric/NeoForge** modpack.

### Steps to reproduce

1. Find any modpack with Forge Mod Loader.
2. Click the download button.
3. After a while, the app crashes with the exception I mentioned below.

### Expected behaviour

Successful download and install of any forge modpack

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/87891239/6e483821-d8ac-4af2-b85b-df1a7462224e)
![image](https://github.com/FTBTeam/FTB-App/assets/87891239/2c4dda5c-1a28-4b4a-8e9d-2d454aec01df)

### Additional information

```
[ftb-app::background.ts] Subprocess stdout [16:57:04] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.task.InstallationOperation]: Fatal exception whilst installing modpack.
net.creeperhost.creeperlauncher.install.InstanceInstaller$InstallationFailureException: Failed to install.
        at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:317) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:49) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-b53a6f5ed2-all.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.io.IOException: Processor output validation errors occurred.
        at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessor(ForgeV2InstallTask.java:338) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessors(ForgeV2InstallTask.java:187) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.execute(ForgeV2InstallTask.java:98) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:260) ~[launcher-b53a6f5ed2-all.jar:?]
        ... 7 more
```
I get this exception every time the app fails to load the modpack

OS: Fedora 40 (kernel version: 6.9.4-200.fc40.x86_64), KDE Plasma: 6.1.0

**Comment by Gaz492** [comment]
Would you be able to go to `~/.ftba/bin/` then rename the libraries folder to libraries-old and try again, the app looks to be running into an issue validating 2 files from minecraft.

**Comment by x1msoc** [comment]
Same expection. I suspect that launcher is getting wrong SHA1 hash from server and fails to validate.

**Comment by Gaz492** [comment]
Does vanilla 1.18.2 work for you?

**Comment by x1msoc** [comment]
I can't create any modpack at all, only download from FTB or CF. Nothing in logs

**Comment by Anroch2020** [comment]
I can confirm that none of the modpacks that use forge <=1.19 can be installed with the linux app, this include curseforge and ftb modpacks, the problem is caused by the modloader installer
Relevant Log:
`9:58:41.242 › [19:58:41][D][ftb-app::background.ts] Subprocess stdout [19:58:41] [Long Running Executor 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Output '/home/achinchilla/.ftba/bin/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-slim.jar' failed to validate.
[19:58:41] [Long Running Executor 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Expected: 2b8907919c1d51fda0b2ace0eba8a8b73855198f
19:58:41.243 › [19:58:41][D][ftb-app::background.ts] Subprocess stdout [19:58:41] [Long Running Executor 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Got     : 647639f51b069331344d5e70ffe625dc87c1eccb
19:58:41.248 › [19:58:41][D][ftb-app::background.ts] Subprocess stdout [19:58:41] [Long Running Executor 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Output '/home/achinchilla/.ftba/bin/libraries/net/minecraft/client/1.18.2-20220404.173914/client-1.18.2-20220404.173914-extra.jar' failed to validate.
[19:58:41] [Long Running Executor 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Expected: 52e1b15676c03b5e1b769f5bd7d89426e9807c89
[19:58:41] [Long Running Executor 0/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Got     : ddfb5452a4d6ddfe4ac59153a19a2e006c8d0a44
[19:58:41] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Processor output validation errors occurred.
19:58:41.253 › [19:58:41][D][ftb-app::background.ts] Subprocess stdout [19:58:41] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.task.InstallationOperation]: Fatal exception whilst installing modpack.
net.creeperhost.creeperlauncher.install.InstanceInstaller$InstallationFailureException: Failed to install.
        at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:317) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:49) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-b53a6f5ed2-all.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.io.IOException: Processor output validation errors occurred.
        at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessor(ForgeV2InstallTask.java:338) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessors(ForgeV2InstallTask.java:187) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.execute(ForgeV2InstallTask.java:98) ~[launcher-b53a6f5ed2-all.jar:?]
        at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:260) ~[launcher-b53a6f5ed2-all.jar:?]
        ... 7 more
19:58:41.253 › [19:58:41][D][ftb-app::background.ts] Subprocess stdout [19:58:41] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.task.LongRunningTaskManager]: Completing LongRunningOp: net.creeperhost.creeperlauncher.task.InstallationOperation@5dfb4c9c
`

**Comment by Anroch2020** [comment]
FTB Neotech and other modpacks that use forge version>=1.20 are installed correctly and without any problem

**Comment by paradust7** [comment]
@Gaz492 The .jar files are failing validation because they have different compression than the ones with the right checksum. The uncompressed contents are identical byte-for-byte, but the jar file is slightly bigger.

```
10857 files, 13319467 bytes uncompressed, 7153550 bytes compressed:  46.3%
10857 files, 13319467 bytes uncompressed, 7195073 bytes compressed:  46.0%
```

These files are being generated by ftb app on the client, from the base file bin/versions/1.18.2/1.18.2.jar
The jar splitter which generates those files is [part of Forge]( https://github.com/MinecraftForge/JarSplitter/blob/master/src/main/java/net/minecraftforge/jarsplitter/ConsoleTool.java#L94-L95).

It uses java.util.zip, might might use the system zlib. And so it could be sensitive to changes in zlib version/config.

**Comment by william-dickinson** [comment]
I can also confirm this behavior running on Fedora 40. I am able to install and run FTB NeoTech but cannot do so with for instance Direwolf20. I've put the relevant lines from my debug.log below - and I am running zlib-ng-compat-2.1.7-1.fc40.x86_64 if that's useful.

```
[23:53:45.160] [Long Running Executor 2/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Output '/home/user/.ftba/bin/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-extra.jar' failed to validate.
[23:53:45.160] [Long Running Executor 2/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Expected: 8c5a95cbce940cfdb304376ae9fea47968d02587
[23:53:45.160] [Long Running Executor 2/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Got     : cf941ba69e11f5a9de15d0c319d61854c456a116
[23:53:45.166] [Long Running Executor 2/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Output '/home/user/.ftba/bin/libraries/net/minecraft/client/1.20.1-20230612.114412/client-1.20.1-20230612.114412-slim.jar' failed to validate.
[23:53:45.166] [Long Running Executor 2/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Expected: de86b035d2da0f78940796bb95c39a932ed84834
[23:53:45.166] [Long Running Executor 2/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]:  Got     : a8fb49bc364562847d6e7e6775e3a1b3f6b2bb05
[23:53:45.166] [Long Running Executor 2/ERROR] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Processor output validation errors occurred.
```

**Comment by william-dickinson** [comment]
After some more investigating looks like this could be the same issue as this PR in forge: https://github.com/MinecraftForge/JarSplitter/pull/2

**Comment by Gaz492** [comment]
Just wanted to check, is everyone here running into an issue running fedora?

**Comment by Gaz492** [comment]
We have released an update to the app which allows you to disable file hash verification.
This can be done by going to Settings > Advanced and enabling the Ignore (Neo)Forge processor hashes checks option.

I will keep this issue open for the time being, in case any further issues arise

**Comment by OffsetMonkey538** [comment]
For me, the same issue happens on Nobara 40 (based on Fedora) when trying to get a 1.20.1 modpack server running while using GraalVM 21, but gets fixed by switching to Temurin 17
