### ISSUE TITLE
Cannot launch NeoForge 1.21

### ISSUE THREAD

**Issue by leagris** [FTBTeam/FTB-App#1169]
### What Operating System

Linux (Other)

### Debug Code

FTB-DBGOLIFEZEWER

### Describe the bug

ATM10 pack crashes before even starting

Note that the pack works perfectly fine with Prism Launcher.

### Steps to reproduce

Install AlltheMods 10
Try to launch
Crashes very early

### Expected behaviour

Should work

### Additional information

```none
[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Pre-Start Tasks Complete
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Java Runtime Validated
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Assets Validated
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Libraries Validated
[FTB APP][INFO] Validate client
[FTB APP][INFO] Client Validated
[FTB APP][INFO] Extract natives
[FTB APP][INFO] Natives Extracted
[FTB APP][INFO] Prepare process
[FTB APP][INFO] Process Prepared
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
Exception in thread "main" java.lang.module.ResolutionException: Modules org.apache.logging.log4j.slf4j2.impl and org.apache.logging.log4j.slf4j export package org.apache.logging.slf4j to module net.neoforged.mergetool.api
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:754)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:196)
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)
```

**Comment by jerry1333** [comment]
And if You change resolution for something normal getting just this:
```
[FTB APP][INFO] Pre-Start Tasks
[FTB APP][INFO] Pre-Start Tasks Complete
[FTB APP][INFO] Validate Java Runtime
[FTB APP][INFO] Java Runtime Validated
[FTB APP][INFO] Validate assets
[FTB APP][INFO] Assets Validated
[FTB APP][INFO] Validate libraries
[FTB APP][INFO] Libraries Validated
[FTB APP][INFO] Validate client
[FTB APP][INFO] Client Validated
[FTB APP][INFO] Extract natives
[FTB APP][INFO] Natives Extracted
[FTB APP][INFO] Prepare process
[FTB APP][INFO] Process Prepared
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
```

**Comment by Mekanofreak** [comment]
Can confirm also getting this issue and that the pack is working fine using the curseforge app, Prism and ATLauncher.

**Comment by Gaz492** [comment]
So vanilla 1.21 works but as soon as I create a neoforge 1.21 instance it also runs into the issue you are running into.
Fabric and forge work fine, so this is only an issue with neoforge modpacks.

**Comment by Gaz492** [comment]
For those using the standalone electron version of the FTB App this issue should be fixed now.
For overwolf, we have set this to be gradually released.
