### ISSUE TITLE
Problem when trying to start Infinity evolved 1.7

### ISSUE THREAD

**Issue by Tomsgaga** [FTBTeam/FTB-App#1202]
### What Operating System

Windows 8.1

### Debug Code

[21:13:30] [Instance Launcher 1/ERROR] [net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler]: Failed to launch instance. net.creeperhost.creeperlauncher.pack.InstanceLaunchException: Failed to prepare instance 'FTB Infinity Evolved 1.7'(fdd1a662-540e-4e62-8b14-c3ef425b5f8b). 	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:514) ~[launcher-c3a5d288d9-all.jar:?] 	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:152) ~[launcher-c3a5d288d9-all.jar:?] 	at net.creeperhost.creeperlauncher.pack.Instance.play(Instance.java:416) ~[launcher-c3a5d288d9-all.jar:?] 	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:56) ~[launcher-c3a5d288d9-all.jar:?] 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?] 	at java.lang.Thread.run(Unknown Source) ~[?:?] Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null 	at net.covers1624.jdkutils.JdkInstallationManager$Installation.migrate(JdkInstallationManager.java:383) ~[launcher-c3a5d288d9-all.jar:?] 	at net.covers1624.jdkutils.JdkInstallationManager$Installation.access$000(JdkInstallationManager.java:366) ~[launcher-c3a5d288d9-all.jar:?] 	at net.covers1624.jdkutils.JdkInstallationManager.<init>(JdkInstallationManager.java:66) ~[launcher-c3a5d288d9-all.jar:?] 	at net.creeperhost.creeperlauncher.Constants.getJdkManager(Constants.java:162) ~[launcher-c3a5d288d9-all.jar:c3a5d288d9] 	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:334) ~[launcher-c3a5d288d9-all.jar:?] 	... 7 more

### Describe the bug

Idk... try to launch the game but 5 sec later there is: "unable to start pack... please see the instance log" and "failed to prepare instance 'FTB Infinity Evolved 1.7' (fdd1a662-540e-4e62-8b14-c3ef425b5f8b). because.. java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonObject()" because "element" is null

### Steps to reproduce

like I mentioned above :(

### Expected behaviour

I´m not the smartest when it comes to certain things. I just want to play the old FTB versions from older times. ;)

**Comment by Tomsgaga** [comment]
Here the debug code:) https://pste.ch/ivugukuqat

**Comment by Gaz492** [comment]
If you go to the settings in the FTB App, you should see 3 buttons under common folders, click on the one named `Home`
This should then open a new window to where the app stores its data, close the app then rename the `bin` folder to `bin_old`
Now start the app up again, right-click the modpack and select settings, you should now see the modpack settings and a repair button. If you click the repair button, this should validate the modpack files and if all goes well, you should be able to play the pack after it's finished repairing.

**Comment by Tomsgaga** [comment]
Thank you very much! Works well! Have a great day! ;)
