### ISSUE TITLE
Launch of every Modpack  - "The instance has crashed or has been externally closed."

### ISSUE THREAD

**Issue by freak1234321** [FTBTeam/FTB-App#1208]
### What Operating System

Windows 11

### Debug Code

https://pste.ch/oboqoseboy

### Describe the bug

As soon as i launch any Modpack, the Launcher starts to launch and crashes at "[FTB APP][INFO] Process Prepared", no matter which modpack.

I tried:

1. Restart
2. Allocating more RAM
3. Login/ Logout - Minecraft Account
4. Un-/Reinstall FTB Launcher
5. Un-/Reinstall Overwolf & FTB Launcher
6. Uninstall/ Update Java 64-Bit [Build 1.8.0_431-b10]

### Steps to reproduce

Launch any Modpack --> The modpack starts to launch but comes to a sudden halt.
And pasts:
"The instance has crashed or has been externally closed." in a red Box.

### Expected behaviour

Launch Modpack

### Screenshots

![grafik](https://github.com/user-attachments/assets/7e8f0068-a459-44b2-82e1-ac415b1042c5)

### Additional information

**console.log**
`Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.IllegalArgumentException
	at java.instrument/sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
	at java.instrument/sun.instrument.InstrumentationImpl.appendToBootstrapClassLoaderSearch(Unknown Source)
	at net.creeperhost.sa.AgentMain.premain(AgentMain.java:34)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message Outstanding error when calling method in invokeJavaAgentMainMethod at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 619
*** java.lang.instrument ASSERTION FAILED ***: "success" with message invokeJavaAgentMainMethod failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 459
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at s\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
`

**Comment by freak1234321** [comment]
A sh.... why did i not come up with this idear.
Yes fixxed it, so no "Ä.Ö.Ü,ß" in your Filepath...

Thank you for your help!
