### ISSUE TITLE
Can't update Star Technology from BETA hotfix 4 to GAMMA hotfix 3

### ISSUE THREAD

**Issue by DrWaffleL0rd** [FTBTeam/FTB-App#1216]
### What Operating System

Windows 10

### Debug Code

v

### Describe the bug

Can't update Star Technology from BETA hotfix 4 to GAMMA hotfix 3
Other modpacks work perfectly fine and can be downloaded and updated

### Steps to reproduce

1. Go to Instances
2. Click Update
3. Update failde due to an unexpected error

### Expected behaviour

Modpack should update fine

### Additional information

[23:21:25.812] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.InstanceInstaller]: File E:\FTB\FTBA\star technology\mods\buildinggadgets-3.16.3-build.26+mc1.19.2.jar has override!
[23:21:25.813] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.InstanceInstaller]: Remapped file path to E:\FTB\FTBA\star technology\mods\buildinggadgets-3.16.3-build.26+mc1.19.2.jar for state ADDED_ENABLED.
[23:21:25.813] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.InstanceInstaller]: File E:\FTB\FTBA\star technology\mods\ftb-ultimine-forge-1902.4.1-build.90.jar has override!
[23:21:25.813] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.InstanceInstaller]: Remapped file path to E:\FTB\FTBA\star technology\mods\ftb-ultimine-forge-1902.4.1-build.90.jar for state ADDED_ENABLED.
[23:21:26.044] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Downloading file C:\Users\******\AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.19.2-47.3.10\forge-1.19.2-47.3.10-installer.jar..
[23:21:26.047] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://maven.creeperhost.net/net/minecraftforge/forge/1.19.2-47.3.10/forge-1.19.2-47.3.10-installer.jar.sha1..
[23:21:26.064] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: Trying to download from https://maven.creeperhost.net/net/minecraftforge/forge/1.19.2-47.3.10/forge-1.19.2-47.3.10-installer.jar..
[23:21:26.132] [Long Running Executor 0/DEBUG] [net.creeperhost.creeperlauncher.install.tasks.DownloadTask]: HTTP/2, Download attempt failed. Attempt 0, URL https://maven.creeperhost.net/net/minecraftforge/forge/1.19.2-47.3.10/forge-1.19.2-47.3.10-installer.jar.
net.covers1624.quack.net.HttpResponseException: status code: 404 , reason phrase: 
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask$DownloadValidation.validateResponseCode(DownloadTask.java:627) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.doRequest(DownloadTask.java:252) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.execute(DownloadTask.java:133) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.AbstractForgeInstallTask.createInstallTask(AbstractForgeInstallTask.java:76) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.modloader.ModLoaderInstallTask.createInstallTask(ModLoaderInstallTask.java:51) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepareModLoader(InstanceInstaller.java:438) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepare(InstanceInstaller.java:213) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:44) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-de7411b37d-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-de7411b37d-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]

[23:21:26.460] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.task.InstallationOperation]: Fatal exception whilst preparing modpack installation.
net.creeperhost.creeperlauncher.task.InstallationOperation$PrepareException: java.lang.IllegalStateException: Failed to prepare ModLoader install task.
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:46) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-de7411b37d-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-de7411b37d-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalStateException: Failed to prepare ModLoader install task.
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepareModLoader(InstanceInstaller.java:445) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepare(InstanceInstaller.java:213) ~[launcher-de7411b37d-all.jar:?]
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:44) ~[launcher-de7411b37d-all.jar:?]
	... 6 more
Caused by: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://maven.creeperhost.net/net/minecraftforge/forge/1.19.2-47.3.10/forge-1.19.2-47.3.10-installer.jar' 6 times.

**Comment by DrWaffleL0rd** [comment]
Can't upload logs either
Error: Failed to upload logs, please try again later

**Comment by MichaelHillcox** [comment]
Please attach a debug code via the applications provided at the bottom of the bots message
