### ISSUE TITLE
[Bug] Launcher fails to start (Linux)

### ISSUE THREAD

**Issue by sayhisam1** [FTBTeam/FTB-App#178]
**Operating System:**
OS: Fedora 30 (Workstation Edition)

**Installer Version:**
Installer: latest

**App Version:**
App: latest

**UI Version:**
UI: not sure

**Log Files:**
only error I seem to be getting is in the `error.log` file after attempting to manually start FTBApp with `./FTBApp`
```
java.lang.ClassNotFoundException: net.creeperhost.creeperlauncher.CreeperLauncher
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:766)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1077)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
        at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
        at install4j.net.creeperhost.creeperlauncher.CreeperLauncher.main(Unknown Source)
Uncaught error fetching image:
java.lang.NullPointerException
        at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:101)
        at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:111)
        at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
        at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
        at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176)
```

**Describe the bug**
The launcher installs correctly, and runs without error the first time after installing. However, any subsequent attempts to open it provide no console output, and generates an `error.log` file.

**To Reproduce**
Not entirely sure what caused the issue, but here is a list of things I did in between the launcher work
Steps to reproduce the behaviour:
1) Run installer
2) Open launcher - it will run as intended
3) Download a modpack
4) Open FTB with a modpack
5) Close FTB (using alt+f4)
6) Reboot computer 
7) Open FTB launcher (fails this time)

**Expected behaviour**
FTB Launcher opens (or atleast provides some console output)

**Additional Context**
Think this might be a java environment issue, but I'm not entirely sure how I would go about fixing it. Any pointers?

**Comment by Mike407** [comment]
Got the same error on Linux Mint 19.3 Tricia.
Same log entry.
But after deinstalling and removing the folder i can not even reinstall.

**Comment by SaltySoltas** [comment]
Also getting this bug on macOS Catalina 10.15.5. Same two exceptions as original poster. Looks like app starts but remains in background for some reason. More details on the tech support sub-forum [here](https://forum.feed-the-beast.com/threads/ftb-app-not-opening-mac.302846/)

**Comment by SaltySoltas** [comment]
I think I found a fix @Cloudhunter. It seems when installing the package onto Mac the "launcher-202006271817-a3b3b73d4c-release-all.jar" file doesn't get properly copied over. I re-downloaded the dmg and dragged that file directly to the spot in the package contents in my applications folder. I started the app back up, and it took a minute but then finally opened.

**Comment by Cloudhunter** [comment]
We did release a new version to fix that issue a few hours ago - perhaps that's why it is now working for you?
