### ISSUE TITLE
[Bug] Launcher Window won't open

### ISSUE THREAD

**Issue by elpis4** [FTBTeam/FTB-App#214]
**Operating System:**
OS: Windows 10

**Installer Version:**
Installer: 202007161516-479dedc615-release

**Log Files:**
launcher.log
> Jul 22, 2020 3:37:06 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: Not a valid instance '.localCache', skipping...

error.log
>SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jul 22, 2020 3:37:06 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: Not a valid instance '.localCache', skipping...
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at net.creeperhost.creeperlauncher.pack.LocalInstance.<init>(LocalInstance.java:150)
	at net.creeperhost.creeperlauncher.Instances.loadInstance(Instances.java:70)
	at net.creeperhost.creeperlauncher.Instances.refreshInstances(Instances.java:52)
	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:215)
	... 12 more
Uncaught error fetching image:
java.lang.NullPointerException
	at java.desktop/sun.awt.image.URLImageSource.getConnection(URLImageSource.java:101)
	at java.desktop/sun.awt.image.URLImageSource.getDecoder(URLImageSource.java:111)
	at java.desktop/sun.awt.image.InputStreamImageSource.doFetch(InputStreamImageSource.java:263)
	at java.desktop/sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:212)
	at java.desktop/sun.awt.image.ImageFetcher.run(ImageFetcher.java:176) 

**Describe the bug**
Launcher is installed, but when launched no window comes up, despite the process being open in Task Manager

**To Reproduce**
Unsure of how to reproduce

**Expected behaviour**
Launcher window to open

**Screenshots**
[No window open while open in Task Manager](https://gyazo.com/e99656a5a1098f68b9ec8d74f2f49457)

**Additional context**
Was previously working, no changes happened between it working and not working, already tried completely reinstalling.

**Comment by KlayTitan** [comment]
not sure if it helps but this is happening for me as well, same error, same results, it was working. And the next time I tried opening it it just sits there, then spits out that error log, and I force close the task. I also tried reinstalling as well as updating Java.

**Comment by KasumiGhia** [comment]
I just suffered the same issue, and found a solution to allow me to continue.
If you 
kill the process, 
delete the .localCache directory, C:\Users\[USERNAME]\.ftba\instances\.localCache
and relaunch the app, it works.
It also rebuilds the directory, so it's not it's existence that is the issue, but something about the contents.
Unfortunately, I didn't save a copy of the broken version for someone to analyze.

**Comment by elpis4** [comment]
No, that didn't fix it for me unfortunately.

**Comment by bold0727** [comment]
I am also experiencing this issue. Deleting my C:\Users\[USERNAME]\.ftba\instances\.localCache doesn't help it. It ran fine when my \instances\ folder was completely empty, so I slowly added files back until I determined that instance.json of FTB Interactions was the cause. I can point my vanilla Minecraft launcher to that folder and it works fine. Other pack's instance.json work fine; for example, if I remove FTB Interactions's instance.json the FTB App will open fine even with FTB Academy with it's instance.json still present in \instances\. I have attached my copy of FTB Interaction's instance.json (renamed to instance.txt to be able to upload). Looking at this file, I can see why it is causing issues. I have not edited this file at all, so I assume this file was corrupted due to a bug. This is definitively the cause of the error for me.
[instance.txt](https://github.com/FTBTeam/FTB-App/files/5009698/instance.txt)

**Comment by elpis4** [comment]
Wow, this fixed it. For me it was actually FTB Omnia, same messed up instance file.

[instance.txt](https://github.com/FTBTeam/FTB-App/files/5009795/instance.txt)

**Comment by bold0727** [comment]
I'm glad to hear that! I'm not sure if it should be closed considering whatever caused the corruption is still an issue though (and this fix barely works as you have to do a clean reinstall to play that modpack again =//)

**Comment by elpis4** [comment]
True, having the instance.json corrupt like that is pretty bad, at least you can save your worlds though.

**Comment by tkolarik** [comment]
I have the same issue with a corrupt instance.json but it appears that way for any pack I download, is there a fixed version of instance.json I could copy and paste in instead?

**Comment by gigabit101** [comment]
We released an update recently that might resolve this issue for you, Can you confirm that the latest version works for you?
