### ISSUE TITLE
Server installer problem

### ISSUE THREAD

**Issue by SkykiritoXH** [FTBTeam/FTB-App#276]
Operating System:
OS:windows 10

Installer Version:
Installer:latest of now

App Version:
App: latest of now

UI Version:
UI: latest of now

Log Files:
Put links to your logs here
how to find logs: no logs

Describe the bug
failed to install server

Context:
Ive just downloaded the server installer for Material energy 5 but when I start to install the server, something like this pops up. Im not sure what to do, ive tried turning the firewall off but it didnt help.

 Unable to download: Connection reset
javax.net.ssl.SSLException: Connection reset
        at sun.security.ssl.Alert.createSSLException(Alert.java:127)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:84)
        at net.creeperhost.modpackserverdownloader.ServerVersion.lambda$install$2(ServerVersion.java:154)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)
Caused by: java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:186)
        at java.net.SocketInputStream.read(SocketInputStream.java:140)
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:165)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
        ... 17 more

**Comment by MichaelHillcox** [comment]
This has likely been fixed with our server installer having been rewritten in a different language. Please reopen if that is not the case
