### ISSUE TITLE
Server downloader connection timeout no retry, files missing

### ISSUE THREAD

**Issue by plaguewolf** [FTBTeam/FTB-App#291]
**Operating System:**
OS: windows 10

**Installer Version:**
Installer: serverinstall_5_121.exe

**App Version:**
App: ?

**UI Version:**
UI: ?

**Log Files:**
N/A

**Describe the bug**

During the download process, occasionally the connection times out and files get skipped over without resume or retry, resulting in a broken install.

Just as a point of fact, this also happens when i use the FTBA launcher...
**To Reproduce**
???

**Expected behaviour**
When a connection timeout occurs, file should not be skipped. resume the download or at least retry or return a fail condition

**Screenshots**

**Additional context**

`[530/3547] Downloaded '01_thermalfoundation_ores.json' to './config/cofh/world/' [26 bytes]...
[530/3547] Unable to download: connect timed out
java.net.SocketTimeoutException: connect timed out
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_net_SocketTimeoutException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
        at com.oracle.svm.jni.functions.JNIFunctions$NewObjectWithObjectArrayArgFunctionPointer.invoke(JNIFunctions.java)
        at com.oracle.svm.jni.functions.JNIFunctions.ThrowNew(JNIFunctions.java:801)
        at java.net.PlainSocketImpl.waitForConnect(PlainSocketImpl.java)
        at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
        at java.net.Socket.connect(Socket.java:609)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:177)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:168)
        at net.creeperhost.creeperlauncher.api.DownloadableFile.prepare(DownloadableFile.java:84)
        at net.creeperhost.modpackserverdownloader.ServerVersion.lambda$install$2(ServerVersion.java:154)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
        at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:138)`

**Comment by MichaelHillcox** [comment]
This should be resolved as our server installer is now written in a different language. Please reopen if this is not the case
