### ISSUE TITLE
trouble installing

### ISSUE THREAD

**Issue by kenkxb** [FTBTeam/FTB-App#362]
I used to use twitch app to download ftb. But now I'm forced to use curseforge, but the native java launcher is ancient and wont let me run anything (curseforge is now useless to me) how are you guys downloading ftb?

message when trying to download from curseforge:
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Gaz492** [comment]
We only provide support for modpacks downloaded using the FTB App, you can find the FTB App from https://feed-the-beast.com
If you are having issues with the FTB App please open a new issue and follow the template.
