### ISSUE TITLE
Minecraft Launcher is not launching

### ISSUE THREAD

**Issue by antoineok** [FTBTeam/FTB-App#367]
Hello, i've downloaded the last version of the FTBApp for linux, but the minecraft launcher won't start, here is the error (i got this one on the java console):
`java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
	at net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:405)
	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.handle(LaunchInstanceHandler.java:23)
	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.handle(LaunchInstanceHandler.java:12)
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10)
	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:126)
	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler$$Lambda$84.000000001C0A8D70.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 6 more`

**Comment by JacobRoth** [comment]
I'm also on Linux and having the minecraft launcher not start when I click Play. I think it has something to do with the launcher archive in ~/.ftba/bin/ not getting extracted properly?

**Comment by carneeki** [comment]
My launcher also will not start, the last part of my logs are pretty similar to @antoineok 's logs, but I have included a few lines earlier.

I am running on Arch Linux, openjdk 1.8.0_265.
UI version: e49e04d4
App version: 202012101153-ce008c54b4-release

```
WARNING: Starting launcher at /home/carneeki/.ftba/bin
Dec. 14, 2020 5:27:18 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:89)
en_AU
Dec. 14, 2020 5:27:18 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:117)
Unable to launch vanilla launcher! 
class java.io.IOException: Cannot run program "/home/carneeki/.ftba/bin/minecraft-launcher/minecraft-launcher": error=2, No such file or directory
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:90)
net.creeperhost.creeperlauncher.pack.LocalInstance.lambda$play$10(LocalInstance.java:534)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1144)
java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3151)
java.base/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1817)
java.base/java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2043)
net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:540)
net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.handle(LaunchInstanceHandler.java:23)
net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.handle(LaunchInstanceHandler.java:12)
net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10)
net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:126)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

Dec. 14, 2020 5:27:18 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:571)
```

**Comment by carneeki** [comment]
Nice find @JacobRoth ; I extracted the tarball, and now encountering a different issue. "Unable to create Mojang Launcher profile", logs say it is trying to read a `launcher_profiles.json` file in both a tmpdir, as well as in `~/.ftba/bin/launcher_profiles.json`, which does not exist.

I'll check the issues and see if there's a solution; I'm thinking the installer needs to do a bit more than simply extract the tarball.

**Comment by carneeki** [comment]
I cleaned out my `~/.ftba` and `/ftba` directories, and did a reinstall; extracted the `minecraft-launcher` directory from the `launcher.tar` file into `~/.ftba` and it kicked off the launcher.

Something in the installer isn't extracting the tarball properly.

**Comment by Logos01** [comment]
Looking at the logfile, FTBA/error.log we see pretty clearly where the issue is occurring.  Somehow the launcher.tar.gz file got included into the extraction path, and given that launcher.tar.gz is a file and not a directory, that's always going to fail. 
`INFO: Downloading Mojang launcher from 'https://launcher.mojang.com/download/Minecraft.tar.gz' to '/home/logos/.ftba/bin/launcher.tar.gz'...
Dec 15, 2020 11:09:54 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Preparing Vanilla Launcher
java.lang.IllegalStateException: Couldn't create directory /home/logos/.ftba/bin/launcher.tar.gz/minecraft-launcher.
	at net.creeperhost.creeperlauncher.util.FileUtils.unTar(FileUtils.java:43)
	at net.creeperhost.creeperlauncher.minecraft.McUtils.prepareVanillaLauncher(McUtils.java:502)
	at net.creeperhost.creeperlauncher.minecraft.McUtils.downloadVanillaLauncher(McUtils.java:378)
	at net.creeperhost.creeperlauncher.minecraft.McUtils.downloadVanillaLauncher(McUtils.java:313)
	at net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask.lambda$execute$0(FTBModPackInstallerTask.java:96)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Dec 15, 2020 11:09:57 PM net.creeperhost.creeperlauncher.CreeperLogger error
`

**Comment by masives** [comment]
I had the similar issue on linux mint 19
However I found in error.log that the minecraft lancher is missing
```
Dec 17, 2020 11:02:39 PM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: Starting launcher at /home/masive/.ftba/bin
Dec 17, 2020 11:02:39 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:89)
en_US
Dec 17, 2020 11:02:39 PM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:117)
Unable to launch vanilla launcher! 
class java.io.IOException: Cannot run program "/home/masive/.ftba/bin/minecraft-launcher/minecraft-launcher": error=2, No such file or directory
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:90)
net.creeperhost.creeperlauncher.pack.LocalInstance.lambda$play$10(LocalInstance.java:534)
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)

```
After copying the entire lancher it worked
`cp /opt/minecraft-launcher /home/masive/.ftba/bin/minecraft-launcher/minecraft-launcher/ -r`

I believe that the ftb is not making a symlink to actual minecraft lancher nor it display error that in gui that lancher is not found

**Comment by Wtfigohere** [comment]
So how can i install an old version? or run it via cla? no mater what version of the script it always install the latest version. so i can play any FTB packs unless i use old client or CF.

**Comment by tautautautautau** [comment]
I got mine working by extracting the "launcher.tar.gz" archive manually in ~/.ftba/bin

There seems to be a problem that the FTBApp (Installer) is not unpacking/extracting the "minecraft-launcher" folder to ~/.ftba/bin

**Comment by ananace** [comment]
Ran into this as well, I noticed that it un-gzips the tarball, but doesn't actually extract it. Perhaps the extraction code isn't built for tarballs.

**Comment by Gaz492** [comment]
If anyone is still having any of the issues mentioned here could you open a new issue provide the information requested by the template and if you have any other useful information also include it.
