### ISSUE TITLE
Error Installing FTB Omnia

### ISSUE THREAD

**Issue by noiseislife** [FTBTeam/FTB-App#37]
I get the following error in the UI, with no obvious way to respond.

Error Installing FTB Omnia - Downloaded file is not the same size. - Retry

This error is in error.log:

`Apr 03, 2020 4:45:46 AM net.creeperhost.creeperlauncher.CreeperLogger warning
WARNING: packicon.png's SHA1 checksum failed.
Apr 03, 2020 4:45:46 AM net.creeperhost.creeperlauncher.CreeperLogger error
SEVERE: net.creeperhost.creeperlauncher.IntegrityCheckException: Downloaded file is not the same size.
java.util.concurrent.CompletionException: net.creeperhost.creeperlauncher.IntegrityCheckException: Downloaded file is not the same size.
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: net.creeperhost.creeperlauncher.IntegrityCheckException: Downloaded file is not the same size.
	at net.creeperhost.creeperlauncher.api.DownloadableFile.validate(DownloadableFile.java:197)
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask.lambda$execute$0(DownloadTask.java:92)
	at net.creeperhost.creeperlauncher.install.tasks.DownloadTask$$Lambda$271.000000000DFE8300.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	... 3 more`

**Comment by CH-Paul-T** [comment]
I think one of the layers of cdn is optimising images... Give me 5 to go check the settings and make sure that isn't turned on.

**Comment by CH-Paul-T** [comment]
Give it a go now please, turned everything I can off.

**Comment by cNorspang** [comment]
I still get the error, towards the end of the download

**Comment by noiseislife** [comment]
Yes, it's working now. Thank you.
