### ISSUE TITLE
[Bug] Modpacks don't launch.

### ISSUE THREAD

**Issue by pixelcmtd** [FTBTeam/FTB-App#399]
**Operating System:**
OS: Linux (Manjaro)

**App Version:**
App: 202101041428-54016a89dc-release

**UI Version:**
UI: 6f769022

**Log Files:**
```
opt/FTBA/FTBApp: line 341: cd: ../jre/bin: No such file or directory
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2021-02-26 19:47:34] [INFO   ] Loaded 1 out of 1 instances. 
[2021-02-26 19:47:34] [INFO   ] No PID args 
java.nio.file.FileSystemException: /opt/FTBA/bin/ftb-app: Operation not permitted
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:254)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:276)
        at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2080)
        at net.creeperhost.creeperlauncher.util.FileUtils.setFilePermissions(FileUtils.java:152)
        at net.creeperhost.creeperlauncher.CreeperLauncher.startElectron(CreeperLauncher.java:544)
        at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:356)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
        at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
        at install4j.net.creeperhost.creeperlauncher.CreeperLauncher.main(Unknown Source)
[2021-02-26 19:47:34] [INFO   ] Starting Electron: /opt/FTBA/bin/ftb-app --ws 13219:c02da02a-e07a-4b2b-855c-7d1928ace09c --pid 93822 
[2021-02-26 19:47:34] [INFO   ] Server started successfully - 202101041428-54016a89dc-release 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19): xdg-mime: application argument missing 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19): Try 'xdg-mime --help' for more information. 
[2021-02-26 19:47:34] [INFO   ] 19:47:34.391 › We have a --ws 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19): 19:47:34.394 › electron-log.transports.file: Can't write to /opt/FTBA/bin/electron.log Error: EACCES: permission denied, open '/opt/FTBA/bin/electron.log' 
[2021-02-26 19:47:34] [INFO   ] 19:47:34.396 › Got the lock 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at Object.openSync (fs.js:440:3) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at Object.func [as openSync] (electron/js2c/asar.js:140:31) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at Object.writeFileSync (fs.js:1265:35) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at l.testFileWriting (/opt/FTBA/bin/resources/app.asar/background.js:1:191555) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at l.createFile (/opt/FTBA/bin/resources/app.asar/background.js:1:191088) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at l.provide (/opt/FTBA/bin/resources/app.asar/background.js:1:190915) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at d (/opt/FTBA/bin/resources/app.asar/background.js:1:188385) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at h (/opt/FTBA/bin/resources/app.asar/background.js:1:187884) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at i (/opt/FTBA/bin/resources/app.asar/background.js:1:21434) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):     at n (/opt/FTBA/bin/resources/app.asar/background.js:1:21226) 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19):  
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19): (ftb-app:93930): Gtk-WARNING **: 19:47:34.420: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19): 19:47:34.521 › (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397 
[2021-02-26 19:47:34] [SEVERE ] net.creeperhost.creeperlauncher.util.StreamGobblerLog.lambda$redirectToLogger$0(StreamGobblerLog.java:19): 19:47:34.531 › (node:93930) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed. 
[2021-02-26 19:47:34] [INFO   ] Front end connected: /127.0.0.1:44788 
[2021-02-26 19:47:49] [WARNING] Starting launcher at /home/chris/.ftba/bin 
[2021-02-26 19:47:49] [SEVERE ] net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:86): en_US 
[2021-02-26 19:47:49] [SEVERE ] net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:114): Unable to launch vanilla launcher! 
java.io.IOException: Cannot run program "/home/chris/.ftba/bin/minecraft-launcher/minecraft-launcher": error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at net.creeperhost.creeperlauncher.minecraft.GameLauncher.launchGame(GameLauncher.java:87)
        at net.creeperhost.creeperlauncher.pack.LocalInstance.lambda$play$12(LocalInstance.java:496)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 10 more
 
[2021-02-26 19:47:49] [SEVERE ] net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:533): Unable to initialize MineTogether Connect! 
```

**Describe the bug**
The modpack doesn't

**To Reproduce**
Steps to reproduce the behaviour:
1. `yay -S ftba`
2. `/opt/FTBA/FTBApp`
3. Install a modpack (I tested Ultimate Reloaded and Monster)
4. Try to launch it
5. See error

**Expected behaviour**
It launches.

**Additional context**
As you can see, it doesn't work, because it can't find the vanilla launcher.

**Comment by MichaelHillcox** [comment]
Looks like a permission issue. Did you get the app from `yay`? A simple fix, although, not the most ideal one `chmod -R 776 /opt/FTBA/`

**Comment by pixelcmtd** [comment]
> Looks like a permission issue. Did you get the app from `yay`? A simple fix, although, not the most ideal one `chmod -R 776 /opt/FTBA/`

I was able to fix it using `sudo chown $USER /opt/FTBA`

**Comment by MichaelHillcox** [comment]
That will work, we just typically don't install into a non-user dir for linux so I was asking how you got it there or if you put it there manually :P Glad you got it fixed :+1:
