### ISSUE TITLE
[Bug]: App not opening

### ISSUE THREAD

**Issue by Hye0Ngit** [FTBTeam/FTB-App#489]
### What Operating System

Windows Insider Preview

### App Version

202203051730-9df8355f62-release

### UI Version

9df8355f62

### Log Files

 SUCCESS  Uploaded bin/settings.json: https://pste.ch/woxaheveku
 WARNING  Uploading bin/launcher_log.txt: failed to open file
 WARNING  Uploading bin/launcher_cef_log.txt: failed to open file
 SUCCESS  Uploaded logs/latest.log: https://pste.ch/cedaxudare
 SUCCESS  Uploaded logs/debug.log: https://pste.ch/lapukezoqu
 SUCCESS  Overwolf Logs: file/directory exists
 SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/index.html.log: https://pste.ch/umiziyulew
 SUCCESS  Uploaded Overwolf/Log/Apps/FTB App/background.html.log: https://pste.ch/efokesemur
 WARNING  Uploading Overwolf/Log/Apps/FTB App/chat.html.log: failed to open file

### Debug Code

FTB-DBGASIKOSIWEZ

### Describe the bug

App makes error Oh! this is bit awkward

### Steps to reproduce

1. Open App

### Expected behaviour

App Opens

### Screenshots

<img width="960" alt="화면 캡처 2022-03-09 124631" src="https://user-images.githubusercontent.com/86336662/157368967-278a633d-b3b7-4550-9df7-ab314e501984.png">

### Additional information

Windows 11 Beta Channel 22000.527

### Information

- [X] I have provided as much information as possible

**Comment by DatApplePy** [comment]
What I did and fixed the issue:
Make backups of each instance.
Delete all the instances and the .localCache folder.
Start FTB App (now it should work).
Download modpacks, replace the "saves" folder of  the newly installed instance with the older one (newer and older instances must match by mods/modpacks they contain).
UI: I hope it will help and sorry  for any error, my english isn't perfect.

**Comment by prog-dude** [comment]
I have the same problem. On Win 10 Pro 20H2. Tried to reinstall the FTB app, nothing changed

**Comment by neverclear86** [comment]
We had the same problem and it was solved.

## Java Access Bridge will not work with it enabled, so disable it.
1. Run this command at the command prompt
    ```
    "%JAVA_HOME%\bin\jabswitch" -disable
    ```
    - `%JAVA_HOME%` may vary depending on your environment, please check your environment variables
2. Restart FTB App

- Reference: [Enabling and Testing Java Access Bridge](https://docs.oracle.com/javase/7/docs/technotes/guides/access/enable_and_test.html)

## Here is the debug.log when an error occurs

```
[08:08:40.228] [main/INFO] [STDOUT]: [net.creeperhost.creeperlauncher.CreeperLauncher:main:92]: e5085ad0fba8e18e596280079e8d3980499e34ece2d0834db5f4710e7b124984
[08:08:40.251] [main/INFO] [Instances]: Reloading instances..
[08:08:40.251] [main/INFO] [Instances]: Skipping Cloud instance reload.
[08:08:40.471] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: java.awt.AWTError: Assistive Technology not found: com.sun.java.accessibility.AccessBridge
[08:08:40.472] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.desktop/java.awt.Toolkit.newAWTError(Toolkit.java:479)
[08:08:40.472] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:495)
[08:08:40.473] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[08:08:40.473] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[08:08:40.473] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1707)
[08:08:40.473] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[08:08:40.474] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[08:08:40.474] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[08:08:40.474] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[08:08:40.474] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[08:08:40.474] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[08:08:40.475] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:544)
[08:08:40.475] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:605)
[08:08:40.475] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.creeperhost.creeperlauncher.pack.LocalInstance.<init>(LocalInstance.java:80)
[08:08:40.475] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.creeperhost.creeperlauncher.Instances.loadInstance(Instances.java:108)
[08:08:40.475] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[08:08:40.475] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[08:08:40.476] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[08:08:40.476] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
[08:08:40.476] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
[08:08:40.477] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:960)
[08:08:40.477] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:934)
[08:08:40.477] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
[08:08:40.477] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
[08:08:40.478] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[08:08:40.478] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:686)
[08:08:40.478] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:927)
[08:08:40.478] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[08:08:40.478] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
[08:08:40.479] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.creeperhost.creeperlauncher.Instances.refreshInstances(Instances.java:72)
[08:08:40.479] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1077]: 	at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:98)
[08:08:40.479] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: Caused by: java.lang.ClassNotFoundException: com.sun.java.accessibility.AccessBridge
[08:08:40.479] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[08:08:40.479] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
[08:08:40.480] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[08:08:40.480] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	at java.base/java.lang.Class.forName0(Native Method)
[08:08:40.480] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	at java.base/java.lang.Class.forName(Class.java:467)
[08:08:40.480] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	at java.desktop/java.awt.Toolkit.fallbackToLoadClassForAT(Toolkit.java:492)
[08:08:40.481] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1086]: 	... 29 more
```

**Comment by dobisan** [comment]
I had the same problem but in a different way. My solution was a non-english character in my windows user folder name. After I made a different user with just english characters in the name, the problem was solved.

**Comment by MichaelHillcox** [comment]
Can you confirm if this is still an issue for you?

**Comment by prog-dude** [comment]
> Can you confirm if this is still an issue for you?

For me no. neverclear86's answer solved it for me
