### ISSUE TITLE
I have a bug with the newest version of the mac launcher

### ISSUE THREAD

**Issue by colk** [FTBTeam/FTB-App#543]
When clicking play on any instance even after redownloading a new mod pack (direwolf 1.18 
202105051826-09e11cc010-preview is the version 
Mac OS Montrey latest version
error is 

[08:17:20] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[08:17:20] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[08:17:20] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Instances directory missing, skipping..
[08:17:20] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 14ms(14297693ns)
[08:17:20] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: No PID args
[08:17:20] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Starting Electron: /Applications/FTBApp.app/Contents/Resources/app/bin/ftbapp.app/Contents/MacOS/ftbapp --ws 10698:1a5cce54-c7ae-4e29-84cb-50c5f90b5f39 --pid 75439
[08:17:20] [WebSocketSelector-25/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Server started successfully - 202105051826-09e11cc010-preview
[08:17:21] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[08:17:21] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[08:17:21] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 0 out of 0 instances in 11ms(11037277ns).
[08:17:21] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 13ms(13080578ns)
[08:17:21] [ForkJoinPool.commonPool-worker-5/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: 08:17:21.260 › We have a --ws
[08:17:21] [ForkJoinPool.commonPool-worker-5/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: 08:17:21.269 › Got the lock
[08:17:21] [ForkJoinPool.commonPool-worker-3/ERROR] [net.creeperhost.creeperlauncher.CreeperLauncher]: 08:17:21.564 › (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
[08:17:21] [ForkJoinPool.commonPool-worker-3/ERROR] [net.creeperhost.creeperlauncher.CreeperLauncher]: 08:17:21.642 › (node:75443) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[08:17:23] [WebSocketWorker-21/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Front end connected: /127.0.0.1:60763
[08:17:29] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask]: Getting pack from api.
[08:17:30] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask]: FTB Presents Direwolf20 1.18 95 2125
[08:17:30] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Installing Minecraft Launcher.
[08:17:30] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Downloading launcher from https://apps.modpacks.ch/FTB2/mac.zip to /Users/kayloebel/Library/Application Support/.ftba/bin/launcherCache/mac.zip
[08:17:31] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Downloaded launcher in 485ms(485101430ns), action taken true.
[08:17:31] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.os.Platform]: Unpacking launcher.
[08:17:31] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask]: Preparing instance folder for /Users/kayloebel/Library/Application Support/.ftba/instances/e53149d0-87d8-445e-b15c-8c3561d0d382
[08:17:31] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.minecraft.modloader.forge.ForgeInstallerModLoader]: Attempting to download https://maven.creeperhost.net/net/minecraftforge/forge/1.18.2-40.1.19/forge-1.18.2-40.1.19-installer.jar.
[08:17:33] [ForkJoinPool-1-worker-5/INFO] [STDOUT]: [net.creeperhost.creeperlauncher.util.ForgeUtils:runForgeInstaller:219]: true
[08:17:33] [ForkJoinPool-1-worker-5/ERROR] [net.creeperhost.creeperlauncher.util.ForgeUtils]: Failed to launch Forge installer.
java.lang.NoSuchMethodException: net.minecraftforge.installer.actions.ClientInstall.<init>(net.minecraftforge.installer.json.Install, net.minecraftforge.installer.actions.ProgressCallback)
        at java.lang.Class.newNoSuchMethodException(Class.java:640) ~[?:?]
        at java.lang.Class.getDeclaredConstructor(Class.java:812) ~[?:?]
        at net.creeperhost.creeperlauncher.util.ForgeUtils.runForgeInstaller(ForgeUtils.java:230) [launcher-202105051826-09e11cc010-preview-all.jar:?]
        at net.creeperhost.creeperlauncher.minecraft.modloader.forge.ForgeInstallerModLoader.install(ForgeInstallerModLoader.java:54) [launcher-202105051826-09e11cc010-preview-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask.installModLoaders(FTBModPackInstallerTask.java:623) [launcher-202105051826-09e11cc010-preview-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask.lambda$execute$0(FTBModPackInstallerTask.java:109) [launcher-202105051826-09e11cc010-preview-all.jar:?]
        at net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask$$Lambda$335/00000000138D1A20.run(Unknown Source) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) [?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) [?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) [?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) [?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) [?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) [?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
[08:17:33] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.minecraft.McUtils]: Attempting to remove forge
[08:17:33] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask]: Attempting to downloaded required files
[08:18:14] [ForkJoinPool.commonPool-worker-7/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Checking for Launch Mod for instance e53149d0-87d8-445e-b15c-8c3561d0d382}(FTB Presents Direwolf20 1.18)..
[08:18:18] [ForkJoinPool.commonPool-worker-7/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Didn't find Launch Mod for instance e53149d0-87d8-445e-b15c-8c3561d0d382(FTB Presents Direwolf20 1.18) in 4108ms(4108592985ns).
[08:18:18] [ForkJoinPool.commonPool-worker-7/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[08:18:18] [ForkJoinPool.commonPool-worker-7/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[08:18:18] [ForkJoinPool.commonPool-worker-7/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 1 out of 1 instances in 1777780ns.
[08:18:18] [ForkJoinPool.commonPool-worker-7/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 3264521ns
[08:19:35] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask]: Getting pack from api.
[08:19:36] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Checking for Launch Mod for instance e53149d0-87d8-445e-b15c-8c3561d0d382}(FTB Presents Direwolf20 1.18)..
[08:19:38] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Didn't find Launch Mod for instance e53149d0-87d8-445e-b15c-8c3561d0d382(FTB Presents Direwolf20 1.18) in 1734ms(1734090423ns).
[08:19:38] [ForkJoinPool-1-worker-5/INFO] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Starting launcher at /Users/kayloebel/Library/Application Support/.ftba/bin
[08:19:38] [ForkJoinPool-1-worker-5/ERROR] [net.creeperhost.creeperlauncher.pack.LocalInstance]: Unable to initialize MineTogether Connect!
[08:19:57] [ForkJoinPool-1-worker-5/INFO] [STDERR]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[08:19:57] [ForkJoinPool-1-worker-5/INFO] [STDERR]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release

**Comment by colk** [comment]
Actually I rebooted the system and it became something else now when I try to launch Direwolf 1.18 mod pack it launches the mojang launcher and when I hit play on the instance it crashes with an exit code 1 My ftb-debug-macos code is
 FTB-DBGCUFIJOCITE
