### ISSUE TITLE
[Bug]: Unable to install modpack on windows if filename contains ":"

### ISSUE THREAD

**Issue by joakime** [FTBTeam/FTB-App#558]
### What Operating System

Windows 10

### App Version

202205171618-14abefffbf-release

### UI Version

14abefffbf

### Log Files

```
2022-05-20 19:06:07,497 (INFO) </dist/background/main.js> (:29) - net.creeperhost.creeperlauncher.install.InstanceInstaller$InstallationFailureException: Failed to install.
2022-05-20 19:06:07,497 (INFO) </dist/background/main.js> (:29) - 	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:261) ~[launcher-202205171618-14abefffbf-release-all.jar:?]
2022-05-20 19:06:07,497 (INFO) </dist/background/main.js> (:29) - 	at net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler.lambda$handleInstall$0(InstallInstanceHandler.java:85) ~[launcher-202205171618-14abefffbf-release-all.jar:?]
2022-05-20 19:06:07,498 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
2022-05-20 19:06:07,498 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
2022-05-20 19:06:07,499 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
2022-05-20 19:06:07,499 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
2022-05-20 19:06:07,499 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
2022-05-20 19:06:07,499 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
2022-05-20 19:06:07,499 (INFO) </dist/background/main.js> (:29) - 	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
2022-05-20 19:06:07,499 (INFO) </dist/background/main.js> (:29) - Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 9: Valhelsia: Enhanced Vanilla - 1.2.2-overrides.zip
2022-05-20 19:06:07,500 (INFO) </dist/background/main.js> (:29) - 	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
2022-05-20 19:06:07,500 (INFO) </dist/background/main.js> (:29) - 	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
2022-05-20 19:06:07,500 (INFO) </dist/background/main.js> (:29) - 	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
2022-05-20 19:06:07,500 (INFO) </dist/background/main.js> (:29) - 	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
2022-05-20 19:06:07,501 (INFO) </dist/background/main.js> (:29) - 	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
2022-05-20 19:06:07,501 (INFO) </dist/background/main.js> (:29) - 	at java.nio.file.Path.resolve(Unknown Source) ~[?:?]
2022-05-20 19:06:07,501 (INFO) </dist/background/main.js> (:29) - 	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest$ModpackFile.getCfExtractPath(ModpackVersionManifest.java:234) ~[launcher-202205171618-14abefffbf-release-all.jar:?]
2022-05-20 19:06:07,501 (INFO) </dist/background/main.js> (:29) - 	at net.creeperhost.creeperlauncher.install.InstanceInstaller.getCFOverridesZip(InstanceInstaller.java:427) ~[launcher-202205171618-14abefffbf-release-all.jar:?]
2022-05-20 19:06:07,502 (INFO) </dist/background/main.js> (:29) - 	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:238) ~[launcher-202205171618-14abefffbf-release-all.jar:?]
2022-05-20 19:06:07,502 (INFO) </dist/background/main.js> (:29) - 	... 8 more
```

### Debug Code

FTB-DBGIHILIPEZIZ

### Describe the bug

Not sanitizing filenames of mods/modpacks on windows

### Steps to reproduce

Install "Valhelsia: Enhanced Vanilla" from curse.

It has a filename of `Valhelsia: Enhanced Vanilla - 1.2.2-overrides.zip` which obviously cannot exist on windows as-is.

### Expected behaviour

Allow install of mods/modpacks even if filenames violate filesystem rules

### Information

- [X] I have provided as much information as possible

**Comment by CoryNB** [comment]
it may be that there is a random ";" ending a command line unexpectedly. please reinstall it clean because it may have been corrupted during download for extraction to fail.

**Comment by joakime** [comment]
It's a full colon (aka `:`), not a semi-colon.
No command line involved at this point.
This is all running within a task on the already running subprocess / backend triggered by a websocket call from the frontend.

The error comes from a (extract) destination filename that's generated by the subprocess / backend using the modpack name `"Valhelsia: Enhanced Vanilla"`, when attempting to execute `getCFOverridesZip()` steps.  

The backend doesn't sanitize modpack names for reserved characters in windows.
So it fails, on windows.  (this step works fine on Linux and OSX)
