### ISSUE TITLE
Invalid CEN header when trying to extract override from curseforge

### ISSUE THREAD

**Issue by JJM152** [FTBTeam/FTB-App#634]
I'm pretty non-plussed by the endless deluge of crappy "mod launchers" I am forced to endure in order to play modded minecraft these days, so imagine my absolute delight when I tried to install Age of Engineering today and was met with the infamous 'Fatal exception wilst installing modpack'. 

A quick look through some folders made it apparent that the issue was that the zip library used in the application cannot read the CEN header on the completely unnecessary "override" zip package that exists only to obfuscate the actual contents of the modpack from the players.  Rather curious since I was able to download the file from the cdn myself and open it quite easily in WinRar.

Relevant exception below:
`[22:00:58.819] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask]: Downloading file C:\Users\jjm15\AppData\Local\.ftba\instances\9f176cf9-8e9d-4d39-b08d-39e0978d867d\.\Age of Engineering-1.1.2.zip-overrides.zip..
[22:00:58.819] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask]:  Trying to download from https://edge.forgecdn.net/files/2503/175/Age%20of%20Engineering-1.1.2.zip..
[22:01:01.250] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask]:   File downloaded.
[22:01:01.250] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.InstanceInstaller]: Extracting CurseForge overrides.
[22:01:01.271] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.task.InstallationOperation]: Fatal exception whilst installing modpack.
net.creeperhost.creeperlauncher.install.InstanceInstaller$InstallationFailureException: Failed to install.
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:269) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:48) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at jdk.nio.zipfs.ZipFileSystem.checkUTF8(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystem.initCEN(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystem.<init>(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(Unknown Source) ~[jdk.zipfs:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at java.nio.file.FileSystems.newFileSystem(Unknown Source) ~[?:?]
	at net.covers1624.quack.io.IOUtils.getFileSystem(IOUtils.java:201) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at net.covers1624.quack.io.IOUtils.getJarFileSystem(IOUtils.java:168) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at net.covers1624.quack.io.IOUtils.getJarFileSystem(IOUtils.java:146) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:245) ~[launcher-202206081143-2e021f8e74-release-all.jar:?]`

**Comment by MichaelHillcox** [comment]
To anwser your actual issue, having proper logs here will help. Our curseforge support is still a little touchy here and there so some packs need debugging to ensure they work.

I will note, the overrides.zip is not our creation, that's a standard system on curseforge.
