### ISSUE TITLE
[Bug]: FTB App Installer Sends out java error and doesn't install

### ISSUE THREAD

**Issue by MrBlyatWasTaken** [FTBTeam/FTB-App#679]
### What Operating System

Linux (Other)

### App Version

FTBA_unix_202208131844-e5790011d3-release

### Log Files

Starting Installer ...
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor (file:/media/data/UsrPrograms/FTBApp/FTBA_unix_202208131844-e5790011d3-release.sh.21056.dir/i4jruntime.jar)
WARNING: Please consider reporting this to the maintainers of com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor
WARNING: System::setSecurityManager will be removed in a future release
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Component
	at java.desktop/javax.swing.ImageIcon$2.run(ImageIcon.java:147)
	at java.desktop/javax.swing.ImageIcon$2.run(ImageIcon.java:145)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.desktop/javax.swing.ImageIcon.createNoPermsComponent(ImageIcon.java:144)
	at java.desktop/javax.swing.ImageIcon$1.run(ImageIcon.java:123)
	at java.desktop/javax.swing.ImageIcon$1.run(ImageIcon.java:120)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/javax.swing.ImageIcon.<clinit>(ImageIcon.java:120)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:195)
	at com.install4j.runtime.installer.frontend.GUIHelper.<clinit>(GUIHelper.java:55)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:81)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.<init>(ConsoleScreenExecutor.java:24)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.<init>(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:91)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:60)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.Installer465309369.main(Unknown Source)
An error occurred:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
Error log: /tmp/install4jError13432257406626116780.log
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:215)
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:234)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:195)
	at com.install4j.runtime.installer.frontend.GUIHelper.<clinit>(GUIHelper.java:55)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:81)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.<init>(ConsoleScreenExecutor.java:24)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.<init>(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:91)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:60)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.Installer465309369.main(Unknown Source)

### Debug Code

FTB-DBGDEJEDULOWO

### Describe the bug

I'm running Linux Fedora, and whenever I attempt to run the installer for the FTB App, I run into this java error saying a terminally deprecated method has been called.

### Steps to reproduce

1. Download the FTB App installer for Linux on the official website
2. Run the installer

### Expected behaviour

FTB App to be installed regularly

### Additional information

I'm running Linux Fedora, and the few results I found about this one error say they are related to java 17, maybe the program is auto detecting the Java 17 installation on my computer, but I also have 1.8.0 and 11 installed, and even when trying to force it to use both, nothing changed.

### Information

- [X] I have provided as much information as possible

**Comment by Pip0une** [comment]
I have the same problem using Pop_OS!
Even when tempting to install java via the script :

Unpacking JRE ...
Starting Installer ...
FTBA_unix_202208131844-e5790011d3-release.sh: 683: /home/pip0une/.ftb/FTBA_unix_202208131844-e5790011d3-release.sh.152404.dir/jre/bin/java: not found

I have used java 17.0.4 and not 17.0.1 like the script want to install, nothing changed.

So i tried to manually install the 17.0.1 and it worked with sudo update-alternatives --install
in my case : sudo update-alternatives --install /usr/bin/java java /home/pip0une/.ftb/jdk-17.0.1+12-jre/bin/java 100

Then using sudo update-alternatives --config java, we can select the java version to use.

Hope it can help someone.

**Comment by Godje** [comment]
I have identical issue to OP
Ubuntu 20.04
Kernel: 5.15
openjdk version "1.8.0_342"
OpenJDK 64-Bit Server VM build 25.342-b07,

**Comment by Anime-pdf** [comment]
Same issue
Fedora Linux 36 (Workstation Edition)
Kernel: 5.19.14-200
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment (Red_Hat-17.0.4.1.1-1.fc36) (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.4.1.1-1.fc36) (build 17.0.4.1+1, mixed mode, sharing)

**Comment by Turakar** [comment]
Same issue
Fedora Linux 37
Tried Java 11 and 17

**Comment by der-eismann** [comment]
I had the same issue on Fedora 37 because I only had `java-11-openjdk-headless` installed. After installing the non-headless `java-11-openjdk` package the installer worked fine.

**Comment by adrylain** [comment]
This is still an issue with OpenJDK 17 and 11 on Fedora 38.

**Comment by Gregam3** [comment]
Same issue on Ubuntu with 8,11 and 17
