### ISSUE TITLE
Support installing the launcher globally (for all users)

### ISSUE THREAD

**Issue by alissonlauffer** [FTBTeam/FTB-App#69]
Would be nice if there's an option to install the launcher globally (for all users). Currently, if you install it in a "system" folder, the launcher will fail to start, as it needs write access to that folder. E.g.:

```
java.nio.file.AccessDeniedException: /usr/share/feedthebeast/launcher.log.lck
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:182)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
        at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
        at java.logging/java.util.logging.FileHandler.openFiles(FileHandler.java:511)
        at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:450)
        at java.logging/java.util.logging.FileHandler.<init>(FileHandler.java:408)
        at net.creeperhost.creeperlauncher.CreeperLogger.<init>(CreeperLogger.java:25)
        at net.creeperhost.creeperlauncher.CreeperLogger.<clinit>(CreeperLogger.java:11)
        at net.creeperhost.creeperlauncher.Instances.refreshInstances(Instances.java:62)
        at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:59)
Apr 08, 2020 10:08:20 AM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Loaded 0 out of 0 instances.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.nio.file.FileSystemException: /usr/share/feedthebeast/bin/ftb-app: Operation not permitted
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:254)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:276)
        at java.base/java.nio.file.Files.setPosixFilePermissions(Files.java:2079)
        at net.creeperhost.creeperlauncher.util.FileUtils.setFilePermissions(FileUtils.java:153)
        at net.creeperhost.creeperlauncher.CreeperLauncher.main(CreeperLauncher.java:78)
```

**Comment by CH-Paul-T** [comment]
We want to, it's a little more complicated, as UAC would stop us storing the instances in that dir, and we've not finished the code changes for customising the data directories yet (Plus all the testing needed)

So this is probably a little way out yet.

**Comment by Dafeader** [comment]
Hi, i know this is really old but i'm having the same problem and I don't understand how to fix it. Installing it in my personal folder (/home/.../FTBA) doesn't help, what's not a "system" folder then?

**Comment by alissonlauffer** [comment]
> Hi, i know this is really old but i'm having the same problem and I don't understand how to fix it. Installing it in my personal folder (/home/.../FTBA) doesn't help, what's not a "system" folder then?

You must install it in a folder you have write access (Don't run it as root).
