### ISSUE TITLE
Server installer fails to read command line arguments

### ISSUE THREAD

**Issue by jikuja** [FTBTeam/FTB-App#79]
If user tries to instal l specific pack or pack version by using command line arguments listed with `--help` installer crashes.

E.g. trying to update omnia to latest version:
```
~/omnia$ ../serverinstall_6_45 6
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
	at java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.lang.String.substring(String.java:1874)
	at net.creeperhost.ftbserverdownloader.Main.main(Main.java:71)
```

Updating omnia to given version
```
~/omnia$ ../serverinstall_6_45 6 46
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 1
	at java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.lang.String.substring(String.java:1874)
	at net.creeperhost.ftbserverdownloader.Main.main(Main.java:71)
```

**Comment by CH-Paul-T** [comment]
Was an oversight on my part, compiling, signing etc replacement binaries now.

I'll note you're using an old version of that executable, unsure if caused by cloudflare cache or just reusing old binaries. (Error is on line 117 now so took me a bit to find it)

**Comment by jikuja** [comment]
True. It was old binary. Can we get --version command line argument for troubleshooting instead of grabbing version number from installer banner?

**Comment by jikuja** [comment]
New version(13c20a7) available in the API and is working as `--help` describes. tyvm

**Comment by CH-Paul-T** [comment]
I'll add --version for the next build, not a bad shout honestly.
