### ISSUE TITLE
Failed to execute asset update task

### ISSUE THREAD

**Issue by NoObPwNeR97** [FTBTeam/FTB-App#832]
### What Operating System

Windows 10

### Debug Code

FTB-DBGJIGOLIVOPO

### Describe the bug

Upon trying to launch any pack on the FTB Launcher it will complete the process up until the Validate Asset task where it fails and a popup is produced. "Java.io.IOException: Failed to execute asset update task" 

### Steps to reproduce

1. Try to run either Oceanblock or Stoneblock

### Expected behaviour

It will run the Pre-Start tasks as well as validate Java Runtime but will almost immediately fail when trying to validate assets

### Screenshots

![Screenshot (1)](https://user-images.githubusercontent.com/50148845/211846616-effc2cb2-fe28-42fd-b882-9bb096f7cfe9.png)

### Additional information

I have done a clean install of FTB, Overwolf, and the modpacks but the same issue remains prevalent, failing to validate assets.

**Comment by ravengangrel** [comment]
I have a very similar issue. I have StoneBlock and OceanBlock installed from a few weeks ago (and they work).

Today I've tried installing other modpacks and all fail with the same error (screenshot attached).

I've tried with Direwolf (both stable and beta), Legend of the Eyes and FTB One, and all of them throw the same exception ("Failed to execute asset update task").
![imagen](https://user-images.githubusercontent.com/7361181/214617721-44c113b4-1469-466f-b304-6c8109e4813d.png)

**Comment by sparquay** [comment]
I also am suffering the same with Stoneblock 3 and Direwolf20 packs.

**Comment by helixbtw** [comment]
Same here, stoneblock 3
![ess](https://user-images.githubusercontent.com/48182352/214648010-cb2ec162-e209-48dd-834d-6f4850c71eb8.png)

**Comment by andriiromaniuk** [comment]
Same with darewolf, any version.
![image](https://user-images.githubusercontent.com/36007327/214650250-45a789f8-345b-4423-b57a-ba17792670eb.png)

**Comment by Dimononon** [comment]
Same with Legend of the Eyes
![image](https://user-images.githubusercontent.com/87992209/214716397-091ef541-a47b-481d-8f89-7b459149a12a.png)

**Comment by ShinmaNoKodou** [comment]
https://pste.ch/mupapoxobe

Same issue, but with Direwolf. Been looking into this for the last twenty minutes. The log shows it failing to download multiple files.  I can open any of those target URLs in Chrome just fine, though.   

Firewalls are completely down, running as admin, updated java...

**Comment by strideynet** [comment]
```
[20:07:56.312] [ForkJoinPool.commonPool-worker-2/ERROR] [net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler]: Failed to launch instance.
net.creeperhost.creeperlauncher.pack.InstanceLaunchException: Failed to prepare instance 'FTB Presents Direwolf20 1.19'(a641f170-c0e3-44c8-8beb-87f8fd1e6683).
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:480) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.launch(InstanceLauncher.java:153) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.LocalInstance.play(LocalInstance.java:392) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.LaunchInstanceHandler.lambda$handle$0(LaunchInstanceHandler.java:52) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.io.IOException: Failed to execute asset update task.
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.checkAssets(InstanceLauncher.java:528) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at net.creeperhost.creeperlauncher.pack.InstanceLauncher.prepareProcess(InstanceLauncher.java:349) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	... 10 more
Caused by: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://resources.download.minecraft.net/b8/b83bbafa9799680da24f10215de2c40b73ce1fe3' 3 times.
Try 0: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
  	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at okio.Throttler$source$1.read(Throttler.kt:140)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
  	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
  	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
Try 1: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
  	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at okio.Throttler$source$1.read(Throttler.kt:140)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
  	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
  	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
Try 2: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
  	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at okio.Throttler$source$1.read(Throttler.kt:140)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
  	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
  	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  

	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:145) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	Suppressed: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
Tried URL: 'https://resources.download.minecraft.net/c9/c9c4d7988a578eccfc31cb2f04defc40d71ef719' 3 times.
Try 0: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
  	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at okio.Throttler$source$1.read(Throttler.kt:140)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
  	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
  	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
Try 1: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
  	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at okio.Throttler$source$1.read(Throttler.kt:140)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
  	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
  	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  
Try 2: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
  	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
  	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at okio.Throttler$source$1.read(Throttler.kt:140)
  	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
  	at okio.ForwardingSource.read(ForwardingSource.kt:29)
  	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
  	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
  	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
  	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  

		at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:145) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
		at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31) ~[launcher-202212152008-a5a6712906-release-all.jar:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
		at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by bemyrequiem** [comment]
I'm getting the same issue but with revelations, when I checked my library it showed an older version of it was installed to I attempted to update it to which I am now getting a "Fatal exception whilst installing modpack" and the modpack doesn't even show on my library now.

**Comment by Yahkub-R** [comment]
What weirdly worked for me is going to :
https://resources.download.minecraft.net/b8/b83bbafa9799680da24f10215de2c40b73ce1fe3 
and saving that into the :
C:\Users\"user"\AppData\Local\.ftba\bin\assets\objects\b8    
folder

**Comment by BodyBagFilla** [comment]
Yea I am stuck on this. Wife and I can't play at all.

**Comment by MichaelHillcox** [comment]
The error here is that you can't download this file 'https://resources.download.minecraft.net/c9/c9c4d7988a578eccfc31cb2f04defc40d71ef719' or any assets from Minecraft. I've seen good results from users that switch over to Cloudflare's DNS (1.1.1.1).

**Comment by Ribuzari** [comment]
I lower my firewall from medium to low and it is fixed. Hope this help

**Comment by MichaelHillcox** [comment]
Hi all, quick update on this, we're looking into the issue now and are hoping for a fix to be going out early next week. We'll keep you posted!

**Comment by Chingy2** [comment]
Was there ever a fix for the issue?

**Comment by MichaelHillcox** [comment]
It should be fixed as long as you're on the latest version

**Comment by kylerentzi** [comment]
> 

it is still not working for me

**Comment by kylerentzi** [comment]
@MichaelHillcox do you know how to fix this issue

**Comment by MichaelHillcox** [comment]
https://appsdl-overwolf-com.akamaized.net/prod/apps/cmogmmciplgmocnhikmphehmeecmpaggknkjlbag/1.23.622.1340/app.opk

Please try with this version of the app. Make sure your current version of the app is closed. Let me know if you have any more issues.

**Comment by Bri-Gadier** [comment]
I am currently experiencing this issue when trying to open Stoneblock 3, and have yet to find a working solution. I've attached my "latest" log and hopefully the relevant .gz file, though I'm not sure what you need for this. 
[latest.log](https://github.com/FTBTeam/FTB-App/files/12089289/latest.log)
[2023-07-18-6.log.gz](https://github.com/FTBTeam/FTB-App/files/12089291/2023-07-18-6.log.gz)

**Comment by TheToastedBread** [comment]
Still having this issue using the most recent version of overwolf.

**Comment by MichaelHillcox** [comment]
Please make a new issue
