### ISSUE TITLE
Stoneblock 3 won't install on the app.

### ISSUE THREAD

**Issue by grumpyfan777us** [FTBTeam/FTB-App#839]
### What Operating System

Windows 11

### Debug Code

Couldn't find the code but uploaded the debug file.

### Describe the bug

Stoneblock 3 has fatal error when trying to download

### Steps to reproduce

1. open the FTB App
2. Click on Browse
3. Press Green install button next to Stoneblock 3
4. release is 3.1.5.0
5. Click Install
6. It returns Fatal Exception whilst installing modpack.
[errorlog1.txt](https://github.com/FTBTeam/FTB-App/files/10452016/errorlog1.txt)

### Expected behaviour

The modpack would install

### Screenshots

![FTB App 1_8_2023 11_06_23 PM](https://user-images.githubusercontent.com/18691551/213318807-72ed4334-9e64-4275-884d-6805a38f4d5d.png)

### Additional information

The launcher used to work fine but I haven't played in about 6-12 months as I'm a truck driver and when I heard about SB3 I wanted to play and it doesn't work.

**Comment by manmaed** [comment]
are you able to rerun the debug tool as it seems it failed to upload the logs

**Comment by benjarex** [comment]
what do you mean by debugging tool

**Comment by benjarex** [comment]
a mí me sucede lo mismo y me gustaría saber como arreglarlo

**Comment by grumpyfan777us** [comment]
> 

 I ran the debug tool 6 times over the course of 3 days with the same result. I attached the debug tool Results in my Original post

**Comment by manmaed** [comment]
what do you get if you go to https://pste.ch/  in your browser?

**Comment by andriiromaniuk** [comment]
@manmaed got same problem, your link works just fine.

**Comment by manmaed** [comment]
@andriiromaniuk can you run the debug tool?  
Please use the link below to download and run the FTB Debug tool. This tool will provide you a code that you can give to the support team which they can use to support your issue more specifically. The code will look like FTB-DBGAOIDOSDII. If you are unsure on how to use this tool, please [follow this guide](https://go.ftb.team/ftbdbg-support).

Download Me
Windows
[ftb-debug.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe)
MacOS
[ftb-debug-macos](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos)
Linux
[ftb-debug-linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)
Windows (Arm)
[ftb-debug-arm64.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug-arm64.exe)
MacOS (Arm)
[ftb-debug-macos-arm64](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos-arm64)
Linux (Arm)
[ftb-debug-linux-arm](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux-arm)

**Comment by andriiromaniuk** [comment]
Here you go.
FTB-DBGXOYAXUWEHO
background.htlm.log says that error was caused by download failed of some music file:
```2023-01-26 00:50:53,163 (INFO) </dist/background/main.js> (:29) - Caused by: net.creeperhost.creeperlauncher.install.tasks.DownloadFailedException: Download failed.
2023-01-26 00:50:53,163 (INFO) </dist/background/main.js> (:29) - Tried URL: 'https://resources.download.minecraft.net/b8/b83bbafa9799680da24f10215de2c40b73ce1fe3' 3 times.
2023-01-26 00:50:53,163 (INFO) </dist/background/main.js> (:29) - Try 0: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:355)
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okio.ForwardingSource.read(ForwardingSource.kt:29)
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okio.Throttler$source$1.read(Throttler.kt:140)
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
2023-01-26 00:50:53,164 (INFO) </dist/background/main.js> (:29) -   	at okio.ForwardingSource.read(ForwardingSource.kt:29)
2023-01-26 00:50:53,165 (INFO) </dist/background/main.js> (:29) -   	at net.covers1624.quack.net.okhttp.ProgressForwardingSource.read(ProgressForwardingSource.java:36)
2023-01-26 00:50:53,165 (INFO) </dist/background/main.js> (:29) -   	at okio.RealBufferedSink.writeAll(RealBufferedSink.kt:190)
2023-01-26 00:50:53,165 (INFO) </dist/background/main.js> (:29) -   	at net.covers1624.quack.net.okhttp.OkHttpDownloadAction.execute(OkHttpDownloadAction.java:119)
2023-01-26 00:50:53,165 (INFO) </dist/background/main.js> (:29) -   	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:203)
2023-01-26 00:50:53,165 (INFO) </dist/background/main.js> (:29) -   	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:121)
2023-01-26 00:50:53,165 (INFO) </dist/background/main.js> (:29) -   	at net.creeperhost.creeperlauncher.install.tasks.ParallelTaskHelper.lambda$executeInParallel$0(ParallelTaskHelper.java:31)
2023-01-26 00:50:53,166 (INFO) </dist/background/main.js> (:29) -   	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
2023-01-26 00:50:53,166 (INFO) </dist/background/main.js> (:29) -   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2023-01-26 00:50:53,166 (INFO) </dist/background/main.js> (:29) -   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2023-01-26 00:50:53,167 (INFO) </dist/background/main.js> (:29) -   	at java.base/java.lang.Thread.run(Unknown Source)```

By the way, I can open the link in Chrome without any trouble and download that file.

**Comment by andriiromaniuk** [comment]
Okay, fixed that with help of my friend who sent me asset folder. There are plenty of posts with people that have same problem, I hope you can somehow send them that folder as temporary fix.

**Comment by grumpyfan777us** [comment]
Somehow, some way its working now out of the blue. I just ran the debug tool again and no issues appeared so I tried installing the game and presto chango! I am playing as I type...YAY!!!

**Comment by StephenPowick** [comment]
This is happening with me as well. Stoneblock 2 seems to work fine, but Direwolf 20 1.19 doesn't work as well as Stoneblock 3

**Comment by osirisgothra** [comment]
It seems that files are not resolving and/or forwarding properly and that ends up appearing as a failed download.

**Comment by osirisgothra** [comment]
> This is happening with me as well. Stoneblock 2 seems to work fine, but Direwolf 20 1.19 doesn't work as well as Stoneblock 3
everyone be sure to update any related apps, you will get problems as they expect to be up to date
