### ISSUE TITLE
Fatal exception whilst installing modpack

### ISSUE THREAD

**Issue by Novocastrian** [FTBTeam/FTB-App#856]
### What Operating System

Windows 11

### Debug Code

FTB-DBGHIVEJIJOTE

### Describe the bug

Fatal error when downloading a modpack

### Steps to reproduce

1. Launch FTB
2. Open FTB settings, make sure the instances directory has lots of space free (5 TB in my case)
3. Search for and download ANY PACK (I'm using FTB Presents Direwolf20 1.19 latest stable build (1.0.1) in this example)
4. It gets stuck at "installing the modloader 0.00% (downloaded files 0/696). Jave Virtual Machine Launcher window appears with the message "A Java Exception has occurred". Clicking the OK button there changes the error message in the FTB download modal to "Fatal exception whilst installing modpack"

### Expected behaviour

Downloaded the modpack without errors

### Screenshots

![Screenshot_20230212_120058](https://user-images.githubusercontent.com/4601813/218262594-6ee56502-8361-443b-99c0-e2810433c6a2.png)
![Screenshot_20230212_120110](https://user-images.githubusercontent.com/4601813/218262596-2150daca-fbd7-4a18-bfdf-1b2d62e8cc8f.png)

### Additional information

I uninstalled FTB and Overwolf, restarted PC, then installed them both, and the issue persisted.

I refreshed the cache in the app, then tried downloading again, issue still persisted again.

https://pste.ch/avosogosin

**Comment by Novocastrian** [comment]
Looking at other issues with the same title ([link](https://github.com/FTBTeam/FTB-App/issues?q=Fatal+exception+whilst+installing+modpack+is%3Aclosed)), some resolved this issue by turning off their antivirus settings. As I only have Windows Firewall, I ensured both Overwolf Browser and Launcher had access through the firewall, but they still couldn't get past this error. Same thing when turning the firewall off altogether. 

I tried downloading the beta version of the DW 1.19 pack, still same issue. 

Seems like a JDK issue to me

**Comment by bigboss2690** [comment]
I am having the same issue with Project Ozone 2 I've not been able to get it to finish the download at all.

**Comment by MichaelHillcox** [comment]
It's failing to move a file... Did you run the app as an admin at any point?

**Comment by bigboss2690** [comment]
No I didn't not that I remember

**Comment by MichaelHillcox** [comment]
Ensure you're not running as an admin and try and resinstall the modpack

**Comment by bigboss2690** [comment]
Ok so it won't install the modpack it gets to to the last two files and
quits and says error

**Comment by MichaelHillcox** [comment]
> Ok so it won't install the modpack it gets to to the last two files and quits and says error

Attach a debug code please

Windows
[ftb-debug.exe](https://dist.creeper.host/tools/ftb-debug/ftb-debug.exe)
MacOS
[ftb-debug-macos](https://dist.creeper.host/tools/ftb-debug/ftb-debug-macos)
Linux
[ftb-debug-linux](https://dist.creeper.host/tools/ftb-debug/ftb-debug-linux)

**Comment by Novocastrian** [comment]
Still having this issue with the latest version of the installer. I confirmed that I was not opening the file as an admin. I could successfully update the existing installation of FTB Presents Direwolf20 1.16 v1.13.2 pack AND installed FTB Unstable 1.20 v 1.3.0 to the same directory (my D drive, a 5TB drive with 4TB free space). I could also downgrade and upgrade the unstable instance versions without issues. It is just this mod pack.

Looking through %localappdata%/.ftba/logs/latest.log, The first exception java logs is this:
`[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 0 in class file sun/misc/Unsafe`

full error:
`[15:14:46] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Starting processor with command 'C:\Users\*******\AppData\Local\.ftba\bin\runtime\jdk-17.0.2+8-jre\bin\javaw.exe -cp C:\Users\*******\AppData\Local\.ftba\bin\libraries\net\minecraftforge\installertools\1.3.0\installertools-1.3.0.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\net\md-5\SpecialSource\1.11.0\SpecialSource-1.11.0.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\com\google\code\gson\gson\2.8.7\gson-2.8.7.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\de\siegmar\fastcsv\2.0.0\fastcsv-2.0.0.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\net\minecraftforge\srgutils\0.4.11\srgutils-0.4.11.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-commons\9.3\asm-commons-9.3.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\com\google\guava\guava\20.0\guava-20.0.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\com\opencsv\opencsv\4.4\opencsv-4.4.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-analysis\9.3\asm-analysis-9.3.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm-tree\9.3\asm-tree-9.3.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\ow2\asm\asm\9.3\asm-9.3.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\apache\commons\commons-text\1.3\commons-text-1.3.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\apache\commons\commons-lang3\3.8.1\commons-lang3-3.8.1.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\commons-beanutils\commons-beanutils\1.9.3\commons-beanutils-1.9.3.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\org\apache\commons\commons-collections4\4.2\commons-collections4-4.2.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\commons-collections\commons-collections\3.2.2\commons-collections-3.2.2.jar;C:\Users\*******\AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.19.2-43.2.14\forge-1.19.2-43.2.14-installer.jar net.minecraftforge.installertools.ConsoleTool C:\Users\*******\AppData\Local\.ftba\bin\libraries\net\minecraftforge\installertools\1.3.0\installertools-1.3.0.jar --task MCP_DATA --input C:\Users\*******\AppData\Local\.ftba\bin\libraries\de\oceanlabs\mcp\mcp_config\1.19.2-20220805.130853\mcp_config-1.19.2-20220805.130853.zip --output C:\Users\*******\AppData\Local\.ftba\bin\libraries\de\oceanlabs\mcp\mcp_config\1.19.2-20220805.130853\mcp_config-1.19.2-20220805.130853-mappings.txt --key mappings'
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Exception in thread "main" java.lang.ClassFormatError: Incompatible magic value 0 in class file sun/misc/Unsafe
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/java.lang.ClassLoader.findBootstrapClass(Native Method)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/java.lang.ClassLoader.findBootstrapClassOrNull(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/java.lang.System$2.findBootstrapClassOrNull(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/jdk.internal.loader.ClassLoaders$BootClassLoader.loadClassOrNull(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/java.lang.Class.forName0(Native Method)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at java.base/java.lang.Class.forName(Unknown Source)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.getUnsafeInstance(UnsafeReflectionAccessor.java:70)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at com.google.gson.internal.reflect.UnsafeReflectionAccessor.<init>(UnsafeReflectionAccessor.java:34)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at com.google.gson.internal.reflect.ReflectionAccessor.<clinit>(ReflectionAccessor.java:36)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at com.google.gson.internal.ConstructorConstructor.<init>(ConstructorConstructor.java:51)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at com.google.gson.Gson.<init>(Gson.java:206)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at com.google.gson.GsonBuilder.create(GsonBuilder.java:597)
[15:14:48] [Stream Gobbler/WARN] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: 	at net.minecraftforge.installertools.ConsoleTool.<clinit>(ConsoleTool.java:31)
[15:14:48] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Processor process exited with non zero exit status. 1
[15:14:48] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask]: Failed to run processor.
java.io.IOException: Processor process exited with non zero exit status code. 1
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessor(ForgeV2InstallTask.java:300) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessors(ForgeV2InstallTask.java:177) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.execute(ForgeV2InstallTask.java:98) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:218) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:48) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-202307221435-df4347b682-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[15:14:48] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.task.InstallationOperation]: Fatal exception whilst installing modpack.
net.creeperhost.creeperlauncher.install.InstanceInstaller$InstallationFailureException: Failed to install.
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:269) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:48) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-202307221435-df4347b682-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.io.IOException: Processor process exited with non zero exit status code. 1
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessor(ForgeV2InstallTask.java:300) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.runProcessors(ForgeV2InstallTask.java:177) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.ForgeV2InstallTask.execute(ForgeV2InstallTask.java:98) ~[launcher-202307221435-df4347b682-all.jar:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:218) ~[launcher-202307221435-df4347b682-all.jar:?]
	... 7 more`

FTB-debug.exe code:  FTB-DBGCOXUKAQADI
Screen recording of the experience attached.

**Comment by Novocastrian** [comment]
I suspect this is related to #870 as they're also having the same issue on the same modpack.

**Comment by Novocastrian** [comment]
Please delete this folder `C:\Users\injur\AppData\Local\.ftba\bin\runtime` and try again.

_Originally posted by @MichaelHillcox in https://github.com/FTBTeam/FTB-App/issues/870#issuecomment-1603300478_

I deleted the `%localaappdata%\.ftba\bin\runtime` folder as per this suggestion, then killed all overwolf processes in the task manager, started the FTB App, and downloaded the `FTB Presents Direwolf20 1.19` modpack. PC crashed part way through the process, but that was an unrelated issue due to EA anti-cheat being installed. 
After restarting the PC and trying this step again, I successfully downloaded the modpack!
![image](https://github.com/FTBTeam/FTB-App/assets/4601813/57886c33-662d-4665-b9dd-5c07579c4ae1)
