### ISSUE TITLE
Not working on Fedora 37

### ISSUE THREAD

**Issue by iosonoagenda** [FTBTeam/FTB-App#866]
### What Operating System

Linux (Other)

### Debug Code

FTB-DBGAFELIRETUS

### Describe the bug

FTB-DBGAFELIRETUS

### Steps to reproduce

1. Download the app
2. chmod +x FTBA_unix_202302201814-1c8edb0091-release.sh
3. ./FTBA_unix_202302201814-1c8edb0091-release.sh

Gives error with java.awt.Component, what to do?
Maybe I am doing something wrong, but I don't know what.

### Expected behaviour

Installed app successfully

### Screenshots

![Schermata del 2023-02-25 12-59-18](https://user-images.githubusercontent.com/54802431/221355644-5e284b6a-726d-4a7d-813e-06c5b3eb81f1.png)

### Additional information

Evenly when tryed to download and install, doesn't work at all. Maybe can be a problem inerhited by Fedora? Or if there is another way to install it please help me out, ok?

**Comment by maygeisler** [comment]
I have the same issue on my system. I'm using:

- Fedora Fedora Linux 38 (Workstation Edition) 64-bit
- Gnome 44.2 on X11
- Linux Kernel Version  6.3.8-200.fc38.x86_64
- The openjdk that comes preinstalled with fedora (openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7, mixed mode, sharing))

and I'm getting the following error while trying to execute the script:
<details>
  <summary>Bash output</summary>
<pre>[mai@fedora Downloads]$ ./FTBA_unix_202306222252-df78a8cfe7.sh 
Starting Installer ...
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor (file:/home/mai/Downloads/FTBA_unix_202306222252-df78a8cfe7.sh.5775.dir/i4jruntime.jar)
WARNING: Please consider reporting this to the maintainers of com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor
WARNING: System::setSecurityManager will be removed in a future release
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Component
	at java.desktop/javax.swing.ImageIcon$2.run(ImageIcon.java:147)
	at java.desktop/javax.swing.ImageIcon$2.run(ImageIcon.java:145)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.desktop/javax.swing.ImageIcon.createNoPermsComponent(ImageIcon.java:144)
	at java.desktop/javax.swing.ImageIcon$1.run(ImageIcon.java:123)
	at java.desktop/javax.swing.ImageIcon$1.run(ImageIcon.java:120)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/javax.swing.ImageIcon.&lt;clinit&gt;(ImageIcon.java:120)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:195)
	at com.install4j.runtime.installer.frontend.GUIHelper.&lt;clinit&gt;(GUIHelper.java:55)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:81)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.&lt;init&gt;(ConsoleScreenExecutor.java:24)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.&lt;init&gt;(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:91)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:60)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.Installer465309369.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can&apos;t load library: /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/lib/libawt_xawt.so [in thread &quot;main&quot;]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.&lt;clinit&gt;(Toolkit.java:1401)
	at java.desktop/java.awt.Component.&lt;clinit&gt;(Component.java:624)
	at com.install4j.runtime.installer.helper.InstallerUtil.initHeadless(InstallerUtil.java:456)
	at com.install4j.runtime.installer.helper.InstallerUtil.isHeadless(InstallerUtil.java:446)
	at com.install4j.runtime.installer.helper.InstallerUtil.getExecutionMode(InstallerUtil.java:437)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:75)
	... 9 more
An error occurred:
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
Error log: /tmp/install4jError1208618650537416968.log
java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/javax.swing.ImageIcon.&lt;init&gt;(ImageIcon.java:215)
	at java.desktop/javax.swing.ImageIcon.&lt;init&gt;(ImageIcon.java:234)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:195)
	at com.install4j.runtime.installer.frontend.GUIHelper.&lt;clinit&gt;(GUIHelper.java:55)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:81)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.&lt;init&gt;(ConsoleScreenExecutor.java:24)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.&lt;init&gt;(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:91)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:60)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.Installer465309369.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can&apos;t load library: /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/lib/libawt_xawt.so [in thread &quot;main&quot;]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.&lt;clinit&gt;(Toolkit.java:1401)
	at java.desktop/java.awt.Component.&lt;clinit&gt;(Component.java:624)
	at com.install4j.runtime.installer.helper.InstallerUtil.initHeadless(InstallerUtil.java:456)
	at com.install4j.runtime.installer.helper.InstallerUtil.isHeadless(InstallerUtil.java:446)
	at com.install4j.runtime.installer.helper.InstallerUtil.getExecutionMode(InstallerUtil.java:437)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:75)
	... 9 more
</pre>
</details>

Contents of the logfile /tmp/install4jError1208618650537416968.log

<details>
  <summary>Logfile</summary>
  <pre>Exception:

java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
	at java.desktop/javax.swing.ImageIcon.&lt;init&gt;(ImageIcon.java:215)
	at java.desktop/javax.swing.ImageIcon.&lt;init&gt;(ImageIcon.java:234)
	at com.install4j.runtime.installer.frontend.GUIHelper.loadIcon(GUIHelper.java:195)
	at com.install4j.runtime.installer.frontend.GUIHelper.&lt;clinit&gt;(GUIHelper.java:55)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.init(AbstractHeadlessScreenExecutor.java:81)
	at com.install4j.runtime.installer.frontend.headless.ConsoleScreenExecutor.&lt;init&gt;(ConsoleScreenExecutor.java:24)
	at com.install4j.runtime.installer.frontend.headless.InstallerConsoleScreenExecutor.&lt;init&gt;(InstallerConsoleScreenExecutor.java:6)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:91)
	at com.install4j.runtime.installer.Installer.runInProcess(Installer.java:60)
	at com.install4j.runtime.installer.Installer.main(Installer.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:66)
	at install4j.Installer465309369.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can&apos;t load library: /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/lib/libawt_xawt.so [in thread &quot;main&quot;]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2393)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:285)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1392)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1390)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1389)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1427)
	at java.desktop/java.awt.Toolkit.&lt;clinit&gt;(Toolkit.java:1401)
	at java.desktop/java.awt.Component.&lt;clinit&gt;(Component.java:624)
	at com.install4j.runtime.installer.helper.InstallerUtil.initHeadless(InstallerUtil.java:456)
	at com.install4j.runtime.installer.helper.InstallerUtil.isHeadless(InstallerUtil.java:446)
	at com.install4j.runtime.installer.helper.InstallerUtil.getExecutionMode(InstallerUtil.java:437)
	at com.install4j.runtime.installer.Installer.getScreenExecutor(Installer.java:75)
	... 9 more

System properties:

java.specification.version=17
install4j.launcherId=777
sun.jnu.encoding=UTF-8
java.class.path=i4jruntime.jar:launcher0.jar
java.vm.vendor=Red Hat, Inc.
sun.arch.data.model=64
install4j.exeDir=/home/mai/Downloads/
sun.font.fontmanager=sun.awt.X11FontManager
java.vendor.url=https://www.redhat.com/
user.timezone=Europe/Berlin
java.vm.specification.version=17
os.name=Linux
sun.java.launcher=SUN_STANDARD
user.country=AU
sun.boot.library.path=/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/lib
sun.java.command=install4j.Installer465309369
jdk.debug=release
sun.cpu.endian=little
user.home=/home/mai
user.language=en
sun.stderr.encoding=UTF-8
java.specification.vendor=Oracle Corporation
java.version.date=2023-04-18
java.home=/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64
file.separator=/
java.vm.compressedOopsMode=Zero based
line.separator=

sun.stdout.encoding=UTF-8
java.vm.specification.vendor=Oracle Corporation
java.specification.name=Java Platform API Specification
exe4j.moduleName=/home/mai/Downloads/FTBA_unix_202306222252-df78a8cfe7.sh
java.awt.headless=true
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
java.runtime.version=17.0.7+7
user.name=mai
path.separator=:
os.version=6.3.8-200.fc38.x86_64
java.runtime.name=OpenJDK Runtime Environment
file.encoding=UTF-8
java.vm.name=OpenJDK 64-Bit Server VM
java.vendor.version=(Red_Hat-17.0.7.0.7-4.fc38)
install4j.jvmDir=/usr/lib/jvm/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64
install4j.cwd=/home/mai/Downloads
install4j.appDir=/home/mai/Downloads/
java.vendor.url.bug=https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&amp;component=java-17-openjdk-portable&amp;version=38
java.io.tmpdir=/tmp
java.version=17.0.7
user.dir=/home/mai/Downloads/FTBA_unix_202306222252-df78a8cfe7.sh.5775.dir
os.arch=amd64
java.vm.specification.name=Java Virtual Machine Specification
exe4j.totalDataLength=1982633
native.encoding=UTF-8
java.library.path=/home/mai/Downloads/FTBA_unix_202306222252-df78a8cfe7.sh.5775.dir/user::/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.vm.info=mixed mode, sharing
java.vendor=Red Hat, Inc.
java.vm.version=17.0.7+7
sun.io.unicode.encoding=UnicodeLittle
java.class.version=61.0
install4j.swt=false
</pre>
</details>

It seems to be a problem with the install4j not the script itself.

I found [this post](https://stackoverflow.com/questions/73203598/i-have-been-trying-to-install-jdownloader2-on-fedora-linux-but-keep-getting-nocl) on stackoverflow with a seemingly similar issue regarding a problem in install4j.

same behavior when executing script as super.

**Comment by JacobCallahan** [comment]
@iosonoagenda @maygeisler If you're still having issues, it may be due to you only having openjdk-headless. You can check with: `rpm -qa | grep openjdk`

If so, then just install the base package and you should be good to go. `sudo dnf install java-17-openjdk`
