### ISSUE TITLE
Failed to retrieve essential information. Please Try again. 

### ISSUE THREAD

**Issue by Giovanni55913** [FTBTeam/FTB-App#926]
### What Operating System

Windows 10

### Debug Code

FTB-DBGQURIWIXAPU

### Describe the bug

It seems that FTB is unable to recognize my minecraft account on microsoft

### Steps to reproduce

1. Open FTB app
2. Login via microsoft account
3. Login to my microsoft account, that has minecraft linked to. 
4. Click on open FTB app
5.  Get erro message
6. I also tried to copy the code given after log in. 

### Expected behaviour

FTB should recognize my account, as vanilla minecraft works fine for. 

### Screenshots

![image](https://github.com/FTBTeam/FTB-App/assets/45241399/b32cc640-f7c8-4859-a7ed-16bcd568a996)
![image](https://github.com/FTBTeam/FTB-App/assets/45241399/610e2764-b3f4-493b-a4a0-2371e07605a9)
![image](https://github.com/FTBTeam/FTB-App/assets/45241399/ffb53a45-89de-48ba-9db2-ff15003ad473)

### Additional information

UI Version: 4c5b6949ca
App Version: 202306081410-4c5b6949ca
Platform: Overwolf
Operating System: WIN

====================================== debug.log =====================================
[18:56:58.586] [main/INFO] [STDOUT]: [net.creeperhost.creeperlauncher.CreeperLauncher:mainImpl:134]: 071cee4f2eb154e8cf8aa0b7bd387a6b8420ee378f70f981ea523c509a9116b4
[18:56:58.607] [main/INFO] [net.creeperhost.creeperlauncher.util.ProxyUtils]: Loading proxy configuration. none  -1, Without Authentication.
[18:56:58.611] [main/TRACE] [net.creeperhost.creeperlauncher.util.SSLUtils]: Injecting LoggingX509TrustManager into OkHTTP.
[18:56:58.614] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[18:56:58.614] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[18:56:58.625] [ForkJoinPool.commonPool-worker-1/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance missing 'instance.json', Ignoring. C:\Users\Giovanni\AppData\Local\.ftba\instances\6ed6d84a-3311-4562-ab22-b81388cf5a5c.zip\instance.json
[18:56:58.942] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 1 out of 1 instances in 324ms(324009700ns).
[18:56:58.942] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 328ms(328416700ns)
[18:56:58.949] [main/INFO] [net.creeperhost.creeperlauncher.CreeperLauncher]: Electron integration mode
[18:56:58.968] [WebSocketSelector-72/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Server started successfully - 202306081410-4c5b6949ca
[18:56:59.439] [WebSocketSelector-72/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: closed /127.0.0.1:53890 with exit code 1000 additional info: 
[18:56:59.439] [WebSocketWorker-56/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Front end connected: /127.0.0.1:53890 - sending our socket and secret and relaunching websocket
[18:56:59.440] [WebSocketWorker-56/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Shutting down websockets on localhost/127.0.0.1:13377
[18:56:59.443] [WebSocketSelector-92/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Server started successfully - 202306081410-4c5b6949ca
[18:56:59.766] [WebSocketWorker-76/INFO] [net.creeperhost.creeperlauncher.api.WebSocketAPI]: Front end connected: /127.0.0.1:53910
[18:57:00.148] [DNS Report Executor 0/INFO] [net.creeperhost.creeperlauncher.util.DNSDebug]: DNS Report:
Chain:
CLOUDFLARE - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
GOOGLE - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
CREEPERHOST - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
System - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Failure
        Result: Query failed.
        Exception:
            java.net.UnknownHostException: Host is onbekend (resolve.modpacks.ch)
            at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
            at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
            at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
            at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
            at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
            at java.base/java.net.InetAddress.getAllByName(Unknown Source)
            at java.base/java.net.InetAddress.getAllByName(Unknown Source)
            at net.creeperhost.creeperlauncher.util.DNSChain$SystemDNSStep.resolve(DNSChain.java:263)
            at net.creeperhost.creeperlauncher.util.DNSChain$StepEntry.runDnsTest(DNSChain.java:175)
            at net.creeperhost.creeperlauncher.util.DNSChain$StepEntry.runSelfTest(DNSChain.java:137)
            at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
            at java.base/java.lang.Thread.run(Unknown Source)
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
Important Hosts:
authserver.mojang.com
    From  : CLOUDFLARE
    Answer: [18.65.39.111, 18.65.39.119, 18.65.39.116, 18.65.39.10]
sessionserver.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.246.67, 13.107.213.67, 2620:1ec:bdf:0:0:0:0:67, 2620:1ec:46:0:0:0:0:67]
launchermeta.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.246.67, 13.107.213.67, 2620:1ec:46:0:0:0:0:67, 2620:1ec:bdf:0:0:0:0:67]
api.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.213.67, 13.107.246.67, 2620:1ec:bdf:0:0:0:0:67, 2620:1ec:46:0:0:0:0:67]
session.minecraft.net
    From  : CLOUDFLARE
    Answer: [13.107.246.67, 13.107.213.67, 2620:1ec:bdf:0:0:0:0:67, 2620:1ec:46:0:0:0:0:67]
piston-meta.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.246.67, 13.107.213.67, 2620:1ec:bdf:0:0:0:0:67, 2620:1ec:46:0:0:0:0:67]
api.modpacks.ch
    From  : CLOUDFLARE
    Answer: [185.57.191.115]
api.creeperhost.net
    From  : CLOUDFLARE
    Answer: [185.57.191.115]
maven.creeperhost.net
    From  : CLOUDFLARE
    Answer: [2606:4700:10:0:0:0:6816:b31, 2606:4700:10:0:0:0:6816:a31, 2606:4700:10:0:0:0:ac43:62b, 104.22.10.49, 104.22.11.49, 172.67.6.43]
maven.fabricmc.net
    From  : CLOUDFLARE
    Answer: [2a06:98c1:3120:0:0:0:0:0, 2a06:98c1:3121:0:0:0:0:0, 188.114.97.0, 188.114.96.0]
maven.minecraftforge.net
    From  : CLOUDFLARE
    Answer: [51.79.83.165, 2607:5300:203:65a5:0:0:0:0]

[18:57:10.960] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[18:57:10.960] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[18:57:10.961] [ForkJoinPool.commonPool-worker-2/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance missing 'instance.json', Ignoring. C:\Users\Giovanni\AppData\Local\.ftba\instances\6ed6d84a-3311-4562-ab22-b81388cf5a5c.zip\instance.json
[18:57:10.968] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 1 out of 1 instances in 7ms(7401100ns).
[18:57:10.968] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 8ms(8426400ns)
[18:57:36.740] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Beginning dance
[18:57:36.741] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Logging into XBox Live
[18:57:36.970] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Logged into XBox live
[18:57:36.970] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Logging into XSTS service
[18:57:37.859] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Logged in successfully to XSTS
[18:57:37.859] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Logging into Minecraft via Xbox
[18:57:38.209] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Logged into Minecraft via Xbox
[18:57:38.209] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Getting profile
[18:57:38.209] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Checking Entitlements
[18:57:38.864] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Request to [https://api.minecraftservices.com/minecraft/profile] isErr with a status code of [404]
[18:57:38.865] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Failed to find Minecraft Profile
[18:57:38.866] [ForkJoinPool-1-worker-3/INFO] [net.creeperhost.creeperlauncher.accounts.authentication.MicrosoftOAuth]: Entitlements show that the does not own minecraft

**Comment by MichaelHillcox** [comment]
You do not own Minecraft on that account. This is typically caused by the migration process migrating to an account you did not intend for it to do so. This is the only outcome of the logs provided.

**Comment by Giovanni55913** [comment]
> You do not own Minecraft on that account. This is typically caused by the migration process migrating to an account you did not intend for it to do so. This is the only outcome of the logs provided.

—————
I know that it states that I do not have an minecraft account. However see screenshot provided I do have minecraft and I also play regular minecraft and curseforge

**Comment by Giovanni55913** [comment]
know that it states that I do not have an minecraft account. However see screenshot provided I do have minecraft and I also play regular minecraft and curseforge

**Comment by MichaelHillcox** [comment]
This may be the case but I can ensure you, you're logging in with the incorrect email address for the **MICROSOFT** Account.

**Comment by Giovanni55913** [comment]
> This may be the case but I can ensure you, you're logging in with the incorrect email address for the **MICROSOFT** Account.

Hi Michael, I can understand what you are saying. However I can assure you that I tried multiple browsers and only have 1 microsoft account. I provided prove and all that I logged in with the correct one.

**Comment by MichaelHillcox** [comment]
Hi, is this still an issue for you? Sorry for the delayed response, I must have missed your reply
