### ISSUE TITLE
Every modpack crash on start

### ISSUE THREAD

**Issue by BrittaNong** [FTBTeam/FTB-App#965]
### What Operating System

Windows 10

### Debug Code

FTB-DBGEYIVOTEPEN

### Describe the bug

Every modpack crash on start

### Steps to reproduce

1. Go to library
2. Click on any modpack
3. Click on Play
4. modpack seems to be loading
5. Crash

### Expected behaviour

Run modpacks

### Additional information

I've tried switching Java versions and it doesn't work. Vanilla versions all work just fine.

The only log I can find is:

Exception in thread "main" java.lang.reflect.InvocationTargetException
FATAL ERROR in native method: processing of -javaagent failed
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.IllegalArgumentException
	at sun.instrument.InstrumentationImpl.appendToClassLoaderSearch0(Native Method)
	at sun.instrument.InstrumentationImpl.appendToBootstrapClassLoaderSearch(InstrumentationImpl.java:195)
	at net.creeperhost.sa.AgentMain.premain(AgentMain.java:34)
	... 6 more

**Comment by stafilokoks** [comment]
I have same issue.

**Comment by MichaelHillcox** [comment]
Looks like this is special chars in the path again @covers1624

**Comment by matthewvines1** [comment]
Same issue here
