### ISSUE TITLE
"Fatal exception" while trying to download pack

### ISSUE THREAD

**Issue by mhork** [FTBTeam/FTB-App#980]
### What Operating System

Linux (Other)

### Debug Code

FTB-DBGAZENUNEWIL

### Describe the bug

fatal error isntead of download

### Steps to reproduce

1. Go to Direwolf20 1.20
2. Download modpack
3. get fatal error instead of download

### Expected behaviour

expected behavior is modpack downloaded sucessfully 

### Screenshots

![Screenshot from 2023-10-17 11-33-56](https://github.com/FTBTeam/FTB-App/assets/39746645/e960b1b6-0047-4f28-a9e1-f3afff1d51e2)

**Comment by derpendary** [comment]
Seconded, and this appears to be a common issue. I'm having much the same on Windows attempting to install All the Mods 9

**Comment by bigtruckin78** [comment]
Got the same error trying to update ATM 9 today.

**Comment by deathbyc4** [comment]
[19:44:53.728] [DNS Report Executor 0/INFO] [net.creeperhost.creeperlauncher.util.DNSDebug]: DNS Report:
Chain:
CLOUDFLARE - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
GOOGLE - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
CREEPERHOST - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Success
        Result: Query success.
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
System - ENABLED - Reports:
    Test: resolve-test: resolve.modpacks.ch - Failure
        Result: Query failed.
        Exception:
            java.net.UnknownHostException: No such host is known (resolve.modpacks.ch)
            at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
            at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
            at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
            at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
            at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
            at java.base/java.net.InetAddress.getAllByName(Unknown Source)
            at java.base/java.net.InetAddress.getAllByName(Unknown Source)
            at net.creeperhost.creeperlauncher.util.DNSChain$SystemDNSStep.resolve(DNSChain.java:263)
            at net.creeperhost.creeperlauncher.util.DNSChain$StepEntry.runDnsTest(DNSChain.java:175)
            at net.creeperhost.creeperlauncher.util.DNSChain$StepEntry.runSelfTest(DNSChain.java:137)
            at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
            at java.base/java.lang.Thread.run(Unknown Source)
    Test: resolve-test: noc.creeper.host - Success
        Result: Query success.
    Test: captive-test: http://captive.modpacks.ch/ - Success
        Result: Query Success.
Important Hosts:
authserver.mojang.com
    From  : CLOUDFLARE
    Answer: [52.85.132.70, 52.85.132.7, 52.85.132.124, 52.85.132.75]
sessionserver.mojang.com
    From  : CLOUDFLARE
    Answer: [2620:1ec:bdf:0:0:0:0:41, 2620:1ec:46:0:0:0:0:41, 13.107.246.41, 13.107.213.41]
launchermeta.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.246.41, 13.107.213.41, 2620:1ec:bdf:0:0:0:0:41, 2620:1ec:46:0:0:0:0:41]
api.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.246.41, 13.107.213.41, 2620:1ec:bdf:0:0:0:0:41, 2620:1ec:46:0:0:0:0:41]
session.minecraft.net
    From  : CLOUDFLARE
    Answer: [13.107.246.41, 13.107.213.41, 2620:1ec:bdf:0:0:0:0:41, 2620:1ec:46:0:0:0:0:41]
piston-meta.mojang.com
    From  : CLOUDFLARE
    Answer: [13.107.213.41, 13.107.246.41, 2620:1ec:bdf:0:0:0:0:41, 2620:1ec:46:0:0:0:0:41]
api.modpacks.ch
    From  : CLOUDFLARE
    Answer: [185.57.191.115]
api.creeperhost.net
    From  : CLOUDFLARE
    Answer: [185.57.191.115]
maven.creeperhost.net
    From  : CLOUDFLARE
    Answer: [2606:4700:20:0:0:0:ac43:4693, 2606:4700:20:0:0:0:681a:505, 2606:4700:20:0:0:0:681a:405, 172.67.70.147, 104.26.5.5, 104.26.4.5]
maven.fabricmc.net
    From  : CLOUDFLARE
    Answer: [172.67.151.177, 104.21.33.240, 2606:4700:3037:0:0:0:6815:21f0, 2606:4700:3033:0:0:0:ac43:97b1]
maven.minecraftforge.net
    From  : CLOUDFLARE
    Answer: [51.79.83.165, 2607:5300:203:65a5:0:0:0:0]

[19:44:58.331] [ForkJoinPool-1-worker-2/INFO] [net.creeperhost.creeperlauncher.data.modpack.ModpackManifest]: Querying Modpack version manifest: https://api.modpacks.ch/public/curseforge/715572
[19:44:59.014] [ForkJoinPool-1-worker-2/INFO] [net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest]: Querying Modpack version manifest: https://api.modpacks.ch/public/curseforge/715572/4830309
[19:44:59.126] [ForkJoinPool-1-worker-2/ERROR] [net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler]: Error preparing Modpack installation.
java.lang.NullPointerException: Cannot invoke "net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest.getStatus()" because "manifest" is null
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest.queryManifest(ModpackVersionManifest.java:152) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest.queryManifest(ModpackVersionManifest.java:137) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.data.modpack.ModpackVersionManifest.queryManifests(ModpackVersionManifest.java:117) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler.handleUpdate(InstallInstanceHandler.java:61) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.InstallInstanceHandler.handle(InstallInstanceHandler.java:40) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.UpdateInstanceHandler.handle(UpdateInstanceHandler.java:10) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.instances.UpdateInstanceHandler.handle(UpdateInstanceHandler.java:5) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.api.handlers.IMessageHandler.handle(IMessageHandler.java:10) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.api.WebSocketMessengerHandler.lambda$handleMessage$0(WebSocketMessengerHandler.java:136) ~[launcher-202310071959-918caed003-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
[19:45:02.854] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Reloading instances..
[19:45:02.854] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Skipping Cloud instance reload.
[19:45:02.856] [ForkJoinPool.commonPool-worker-3/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Deathbyc4\AppData\Local\.ftba\instances\6449cd3b-a3a4-4e89-b129-88f411034e8a\instance.json
[19:45:02.857] [ForkJoinPool.commonPool-worker-5/WARN] [net.creeperhost.creeperlauncher.Instances]: Instance install never completed, Ignoring. C:\Users\Deathbyc4\AppData\Local\.ftba\instances\abc54f32-0043-47bc-8fbc-b98640a9940b\instance.json
[19:45:02.864] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Loaded 3 out of 3 instances in 8ms(8527800ns).
[19:45:02.864] [main/INFO] [net.creeperhost.creeperlauncher.Instances]: Finished instance reload in 9ms(9660000ns)

**Comment by Sn0oZemc** [comment]
I'm having a similar problem, also with trying to download ATM9...

**Comment by deathbyc4** [comment]
looks Ike its been resolved, mustve been an issue on creeperhosts end.

**Comment by Maceris** [comment]
I am still facing this issue with GT: New Horizons. There are no console logs, but the app itself complains about a missing manifest in logs.

Launching pack - https://pste.ch/poyejofezu
Downloading pack - https://pste.ch/uvudaqeyum
