### ISSUE TITLE
Windows defender catching jar-installation file as mallicious - Stoneblock 3 1.8.0

### ISSUE THREAD

**Issue by mathias852** [FTBTeam/FTB-App#988]
### What Operating System

Windows 10

### Debug Code

FTB-DBGLUPUDABEPA

### Describe the bug

Win 10 defender catching forge-1.18.2-40.2.10-installer.jar as mallicious

### Steps to reproduce

Just regularlly installing windows defender running. Opening FTB launcher and installing the Stoneblock 3 instance like any new; not this is only apparent on modpack-version 1.8.0. 

The instance-installer class tries to create a new minecraft instance, based on the downloaded manifest, however before it can do that Windows defender catches the installer-jar as mallicious. Which results in the application to trying 6 times, unsuccesfully and resulting in the UI message: 'Fatal error has occurred.'

`Try 5: java.nio.file.FileSystemException: C:\Users\REDACTED\AppData\Local\.ftba\bin\libraries\net\minecraftforge\forge\1.18.2-40.2.10\forge-1.18.2-40.2.10-installer.jar: Operation did not complete successfully because the file contains a virus or potentially unwanted software
  	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
  	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
  	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
  	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
  	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
  	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
  	at java.base/java.nio.file.Files.newInputStream(Unknown Source)
  	at net.covers1624.quack.util.MultiHasher.load(MultiHasher.java:75)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.hash(NewDownloadTask.java:379)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.validateDownload(NewDownloadTask.java:348)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.doRequest(NewDownloadTask.java:344)
  	at net.creeperhost.creeperlauncher.install.tasks.NewDownloadTask.execute(NewDownloadTask.java:144)
  	at net.creeperhost.creeperlauncher.install.tasks.modloader.forge.AbstractForgeInstallTask.createInstallTask(AbstractForgeInstallTask.java:73)
  	at net.creeperhost.creeperlauncher.install.tasks.modloader.ModLoaderInstallTask.createInstallTask(ModLoaderInstallTask.java:49)
  	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepareModLoader(InstanceInstaller.java:354)
  	at net.creeperhost.creeperlauncher.install.InstanceInstaller.prepare(InstanceInstaller.java:178)
  	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:43)
  	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74)
  	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111)
  	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  	at java.base/java.lang.Thread.run(Unknown Source)`

### Expected behaviour

Windows should now catch the installer-jar file as mallicious, thus completing the full download and setup of the mc-instance

**Comment by MichaelHillcox** [comment]
Not an app issue but this should have been resolved. This as never a virus, just windows being silly
