### ISSUE TITLE
Importing modpack fails if there are no config overrides

### ISSUE THREAD

**Issue by tlannigan** [FTBTeam/FTB-App#997]
### What Operating System

Windows 10

### Debug Code

N/A

### Describe the bug

Modpack importing fails if the modpack zip file does not contain an "overrides" folder.

### Steps to reproduce

1. Export a modpack from Curseforge that doesn't have any config files changed (thus producing no "overrides" folder in the archive)
2. Try to import it into the FTB App

### Expected behaviour

Modpack should be imported

### Additional information

Relevant FTB App `latest.log` portion:

```
[18:29:06] [Long Running Executor 0/INFO] [net.creeperhost.creeperlauncher.install.InstanceInstaller]: Extracting CurseForge overrides.
[18:29:06] [Long Running Executor 0/ERROR] [net.creeperhost.creeperlauncher.task.InstallationOperation]: Fatal exception whilst installing modpack.
net.creeperhost.creeperlauncher.install.InstanceInstaller$InstallationFailureException: Failed to install.
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:269) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.task.InstallationOperation.doOperation(InstallationOperation.java:48) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.creeperhost.creeperlauncher.task.LongRunningOperation.lambda$wrapOperation$0(LongRunningOperation.java:74) ~[launcher-202310071959-918caed003-all.jar:?]
	at net.covers1624.quack.util.SneakyUtils.lambda$concat$9(SneakyUtils.java:111) ~[launcher-202310071959-918caed003-all.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.nio.file.NoSuchFileException: /overrides
	at jdk.nio.zipfs.ZipPath.readAttributes(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipPath.readAttributes(Unknown Source) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(Unknown Source) ~[jdk.zipfs:?]
	at java.nio.file.Files.readAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.getAttributes(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.visit(Unknown Source) ~[?:?]
	at java.nio.file.FileTreeWalker.walk(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at java.nio.file.Files.walkFileTree(Unknown Source) ~[?:?]
	at net.creeperhost.creeperlauncher.install.InstanceInstaller.execute(InstanceInstaller.java:247) ~[launcher-202310071959-918caed003-all.jar:?]
	... 7 more
```

A manual solution to this issue is to add an empty "overrides" folder in the modpack archive, allowing the modpack to be imported successfully.

**Comment by tlannigan** [comment]
I created this issue on behalf of another user that I was troubleshooting with, I don't remember what modpack this was for or have access to it. If the app is allowing you to import modpacks without `/overrides` folder in them, I would consider my issue closed.
